### ISSUE TITLE
Need a coding convention

### ISSUE THREAD

**Issue by jbkoh** [BrickSchema/Brick#104]
We need a coding convention to follow in the projects in Brick. I personally follow PEP8 with 100 chars per line for Python, but happy to settle with anything else.

I am just creating this issue for now so that we can refer to it later as a future task.

**Comment by JoelBender** [comment]
[Black](https://black.readthedocs.io/en/stable/) and [Mypy](https://mypy.readthedocs.io/en/stable/) work for me, some folks include [isort](https://timothycrosley.github.io/isort/).

**Comment by gtfierro** [comment]
[Black](https://github.com/psf/black) is nice because it doesn't have "any" configuration options, which means that we can't spend anymore time bike-shedding the Python style :). [yapf](https://github.com/psf/black) also looks good. I'd just like it to adhere to some standard, and to not deviate unless we have a good reason. Any thoughts?

**Comment by jbkoh** [comment]
Thanks for the suggestions!

For formatting, I vote for Black. 

There are also non-formatting conventions such as [True/False Evaluation](http://google.github.io/styleguide/pyguide.html#214-truefalse-evaluations) I don't think Black can format such things as well, can it?

So, I'd suggest to follow everything defined in Black. Otherwise, follow Google Python conventions.

**Comment by shreyasnagare** [comment]
I tried both `yapf` and `Black` and found `yapf` to produce non-deterministic results. `Black` really is uncompromising. :)

Let's go with Black.

**Comment by gtfierro** [comment]
Sounds like we're going with Black. Does anyone have any issues with the implementation in https://github.com/BrickSchema/Brick/pull/106?

**Comment by gtfierro** [comment]
Closed with #106 being merged!
