### ISSUE TITLE
AHU definition != Air_Handler_Unit definition

### ISSUE THREAD

**Issue by corymosiman12** [BrickSchema/Brick#145]
Hey Gabe - congrats on the 1.1.0 release!  Looking forward to going through it!

I think this is a mistake?  The definition looks like it should be for a differential pressure sensor or something...

https://github.com/BrickSchema/Brick/blob/54847b9419836fa29c21f8d7815b24f632b7ec9b/Brick.ttl#L9282-L9286

**Comment by gtfierro** [comment]
Oh, good catch! I'll push a fix soon

**Comment by gtfierro** [comment]
@corymosiman12 we'll be updating the website soon with the updated classes and definitions: small technical bug holding up that update for now. This repo will be up to date though
