### ISSUE TITLE
v1.1.0 Definitions

### ISSUE THREAD

**Issue by corymosiman12** [BrickSchema/Brick#147]
## Heat Exchanger
`A system that transfers heats between two or more fluids`

This should be more generic, as in:

`A system that transfers heat between two or more substances`

BEDES definition:
`A heat exchanger is a piece of equipment built for efficient heat transfer from one medium to another. The media may be separated by a solid wall to prevent mixing or they may be in direct contact.`

You could then probably subtype to different heat exchanger mechanisms based on the source and sink, i.e.:
- air to air
- air to water
... etc.

I also think we need to consider what the difference / similarities between the `Coil` and `Heat_Exchanger` concepts is.  

## Coil
`Exchanger that transfers heat to or from an exhaust airstream to a separated supply airstream.`

This also doesn't make sense to have only limited to exhaust and supply airstreams.  My only intuition on it is that coils are 'generally' thought of as being interior to an AHU / Terminal Unit.  BEDES doesn't provide a definition for coil.

ASHRAE defines Coil: 
`cooling or heating element made of pipe or tube that may or may not be finned and formed into helical or serpentine shape.`

**Comment by gtfierro** [comment]
Thanks for taking the time to go through some of these and point this out! I'll be honest that I completely forgot about BEDES when I was putting together some of these definitions --- these edits definitely make sense. I"ll propose some changes in a PR soon; I'll tag you so you can provide some feedback if you have time

**Comment by gtfierro** [comment]
Can you take a look at https://github.com/BrickSchema/Brick/pull/160 to see if its a satisfactory fix?

**Comment by gtfierro** [comment]
Merged #160
