### ISSUE TITLE
Virtual Buildings Information System (VBIS)

### ISSUE THREAD

**Issue by heshans2020** [BrickSchema/Brick#148]
Hello,

Not sure if this is the right place, however I could not locate any other contact details.

VBIS is an freely available open standard that provides a comprehensive classification system for all types of assets within the built environment. It was developed with funding from the Government and is part of a couple of Government frameworks in digital asset construction and asset management. Along with the classification tables, VBIS provides unique tags for specific asset identification. And there is also a mechanism specified to allow searching and displaying asset information located in different software applications. 

There appears to be good alignment between the development of Brick that tackles the relationship with the field in great detail by defining the I/O and VBIS that standardises on all the different asset/equipment types. 

Would it be possible to discuss further with anyone?

Thanks.
Heshan.
www.vbis.com.au

**Comment by gtfierro** [comment]
Hi there @heshans2020! Thanks for reaching out. VBIS looks like a very relevant and interesting project and we would be interested in discussing more with you. Can you send me an email (you can find it at https://people.eecs.berkeley.edu/~gtfierro/) so we can set up a meeting? @jbkoh I'll CC you on the email thread once it is established

**Comment by heshans2020** [comment]
Hi @gtfierro ! Thanks for the reply. I just sent an email. Look forward to discussing further.
