### ISSUE TITLE
Weather as subclass of Equipment?

### ISSUE THREAD

**Issue by corymosiman12** [BrickSchema/Brick#149]
This doesn't make sense to me.  In BSync / BEDES, we have [Weather Station](https://bedes.lbl.gov/bedes-online/weather-station), and I know oftentimes commercial buildings have their own weather station, which I think could be considered an equipment.

**Comment by gtfierro** [comment]
This is an artifact of Brick v1.0.3; I like the idea of including Weather Station instead. Weather points (which we do have) could be associated with that equipment

**Comment by gtfierro** [comment]
Got a proposed fix in https://github.com/BrickSchema/Brick/pull/161 ; I'll leave it open for today in case there are any suggestions

**Comment by gtfierro** [comment]
Fixed in https://github.com/BrickSchema/Brick/pull/161
