### ISSUE TITLE
Supply_Fan and Discharge_Fan

### ISSUE THREAD

**Issue by corymosiman12** [BrickSchema/Brick#150]
Should these be an `owl:equivalentClass`?

**Comment by gtfierro** [comment]
We've heard some amount of disagreement on this over the years: some people insist that these two are equivalent and others say that they are distinct concepts, but I haven't seen an authoritative reference either way. Do you have or know of one? I'd be happy to amend the definitions to match

**Comment by corymosiman12** [comment]
Mine is just all through the grapevine.  It has mainly been a context perspective.  It is the 'discharge' of the current thing, but it is the 'supply' when it is to something else:
- "Air is supplied to the VAV from the AHU"
- "Air is supplied to the zone from the VAV"
- "Air leaves the AHU from the discharge duct"

Probably other people with examples as well.  I don't have too much of a strong opinion on it either way, but I'm sure some people will.

**Comment by gtfierro** [comment]
I'll edit them to be equivalent for the next release (https://github.com/BrickSchema/Brick/pull/162) and will take a pass for making sure that the supply/discharge equivalencies are handled correctly in the rest of the class structure
