### ISSUE TITLE
Filter hierarchy and definition

### ISSUE THREAD

**Issue by corymosiman12** [BrickSchema/Brick#152]
Your definition should probably also include the (3) definition from ASHRAE - `device to remove solid material from a fluid`.  I would then probably subclass an `Air_Filter`, then finally a `Mixed_Air_Filter`.

Might want to also consider the concepts of `Pre_Filter` and `Final_Filter`, as these are also important concepts / distinctions.  Unfortunately I didn't find a good definition for `Final_Filter`...  

Prefilter:
- https://qr.ae/pNs25y

**Comment by gtfierro** [comment]
Thanks for the issue! Took a stab at the definitions for those concepts in https://github.com/BrickSchema/Brick/pull/163

**Comment by gtfierro** [comment]
Fixed in https://github.com/BrickSchema/Brick/pull/163
