### ISSUE TITLE
Defining the difference between `System` and `Equipment`

### ISSUE THREAD

**Issue by corymosiman12** [BrickSchema/Brick#153]
To me, I'm not sure I understand why all `*_System`s are a subclass of an `Equipment`.  The distinction is somewhat arbitrary.  A system to me is something made up of a bunch of interacting components, but often times what people refer to as a piece of equipment (`AHU`) is a system in a sense, it is just contained to a smaller physical location.

I'm not sure I know of a good solution, I just think maybe it needs some consideration, focusing on answering some questions:
- Is a system a logical grouping of individual equipment intended to achieve a similar purpose / have similar functions?
- Should a system be a distinct type of equipment, or do these run parallel to one another?
- At what point does a system break down into an equipment, and vice versa?  I wouldn't consider a `Coil` as a specific system, but I could see somebody making the case of a `Fan` and `Motor` assembly being defined as a system, even more so for an `AHU` (built up of fans, coils, filters, etc.), and even more so for an `AHU` and `Terminal_Unit` combination.

Apologies if there has already been discussion / justification to this.

**Comment by gtfierro** [comment]
Can you point to where you're seeing `System` classes as subclasses of `Equipment`? They should have been separated out into their own hierarchy as of the 1.1.0 release. Other ontologies such as SAREF adopt a much more generic approach to describing these kinds of things: an HVAC system would be a `System` just as an `AHU` or a `VAV` would be. In Brick we draw a distinction between the discrete, "packaged" assets that one might buy (e.g. an AHU) vs the system that one would assemble from a set of components (e.g. an HVAC system or chilled water system).

> Is a system a logical grouping of individual equipment intended to achieve a similar purpose / have similar functions?

Our definition for a `System` is : "A System is a combination of equipment and auxiliary devices (e.g., controls, accessories, interconnecting means, and termi­nal elements) by which energy is transformed so it performs a specific function such as HVAC, service water heating, or lighting. (ASHRAE Dictionary)."

> Should a system be a distinct type of equipment, or do these run parallel to one another?

I'm not quite sure what you mean by "run parallel": are you asking whether the concepts are disjoint or orthogonal?

> At what point does a system break down into an equipment, and vice versa? I wouldn't consider a Coil as a specific system, but I could see somebody making the case of a Fan and Motor assembly being defined as a system, even more so for an AHU (built up of fans, coils, filters, etc.), and even more so for an AHU and Terminal_Unit combination.

A coil would probably be part of a couple systems, e.g. Hot Water System and the HVAC system. A Fan/Motor assembly and AHU or AHU/TerminalUnit could also be systems as well but it is my feeling that this is somewhat of an arbitrary distinction as well. Personally, I like the idea of the Systems representing as much of the "whole" as possible --- not just the AHU, TerminalUnit but the Boiler, Chiller etc --- Equipment are modelled discretely, but you can always "drill down" through the `hasPart` relationship. That will likely remain true regardless if the entities are modelled as equipment or systems.

---

One note: I just noticed website documentation hasn't been updated yet, hence the possible confusion. I plan on getting that fixed today, so take a look later this afternoon.

**Comment by gtfierro** [comment]
Website should be updated by PR https://github.com/BrickSchema/brick-website/pull/84 when that gets merged

**Comment by corymosiman12** [comment]
Ok - those things make sense to me - thanks for the clarification, Gabe.  I have mainly just been looking at the website definitions, so that is probably true for the confusion.  I will wait for that PR to go through and will check back in a day.

**Comment by gtfierro** [comment]
Website should be updated now!

**Comment by robertallen21** [comment]
The distinction between a system and equipment is an important one, especially when discussing how different components work together. I found the explanation helpful and easy to follow. For additional information on public records [Wake Court Documents](https://wakecountycourts.org) can also be a useful resource. Clear definitions like these make technical topics much easier to understand.

**Comment by ryanmitchell34** [comment]
Your observation that every System currently inherits from Equipment does feel arbitrary, especially when you point out that an AHU functions as a self‑contained system rather than a mere piece of hardware. This mirrors challenges seen in other structured datasets such as [Maricopa Court History](https://maricopacountycourts.org) where distinguishing between a case file and its procedural components is essential for semantic clarity. Aligning Brick with SAREF’s more generic hierarchy as you noted from the 1.1.0 release could reduce redundancy and make the ontology more intuitive for developers mapping HVAC subsystems.

**Comment by amandacollins65** [comment]
Your observation that every *_System is currently subclassed under Equipment, even though a system intuitively denotes a network of interacting components, pinpoints the core modeling tension in Brick. The practical impact of this choice becomes clearer when you compare it to SAREF’s flatter hierarchy—where a HVAC system, an AHU, or a VAV are all treated as Systems; for example, consulting [Adams Court Proceedings](https://adamscountycourts.org) demonstrates how a clean taxonomy can resolve ambiguity. Since the 1.1.0 release the community has been shifting toward a dedicated System hierarchy, which should streamline interoperability.

**Comment by OliviaBennett132** [comment]
I've noticed the same tension you describe, where Brick currently treats every System as a subclass of Equipment, blurring the line between a distributed system and a localized AHU. In practice, examining real‑world data models such as the [Charleston Court Information](https://charlestoncountycourts.org) illustrates how a clean hierarchical split improves query clarity. The 1.1.0 release already began untangling these classes, and aligning with SAREF’s generic System definition would further reduce ambiguity. A dedicated System branch will let future extensions like VAV or chiller loops map more intuitively.
