### ISSUE TITLE
VFD Definition

### ISSUE THREAD

**Issue by corymosiman12** [BrickSchema/Brick#154]
Currently: `An alarm that indicates a loss of water e.g. during transport`

BEDES: https://bedes.lbl.gov/bedes-online/variable-frequency-drive

ASHRAE: https://xp20.ashrae.org/terminology/index.php?term=vfd&submit=Search

**Comment by corymosiman12** [comment]
I didn't realize - you actually use the ASHRAE definition already for `Variable_Frequency_Drive`, so just update to match the two.

**Comment by gtfierro** [comment]
Good catch! Fix is in https://github.com/BrickSchema/Brick/pull/164

**Comment by gtfierro** [comment]
Fixed in https://github.com/BrickSchema/Brick/pull/164
