### ISSUE TITLE
Heating_Valve and Cooling_Valve Class hierarchy

### ISSUE THREAD

**Issue by corymosiman12** [BrickSchema/Brick#155]
Given that a `Heating_Valve` distinctly defines '...modulating the amount of hot water...' (similar to `Cooling_Valve`), should these not be subclasses of `Water_Valve`?  Unless the definitions for heating valve and cooling valve were changed to specify `...modulating the amount of a substance...`, which would enable them to be more generic and allow something like a `Steam_Valve` to be a specific type of `Heating_Valve`.

Just something to consider.

**Comment by gtfierro** [comment]
It is probably a better move to remove the "water" from the generic definition; we already have `Hot_Water_Valve` which is a subclass of both Heating Valve and Water Valve.

And really, the heating valve isn't specific to Air either. I'll need to source or derive a good generic definition for the heating/cooling valve classes

**Comment by corymosiman12** [comment]
Hey Gabe - I just looked and there is no distinct `Hot_Water_Valve`.  There is one for domestic and one for preheat.  Not sure what the right call is on making that a new distinct class, just wanted to let you know.

**Comment by gtfierro** [comment]
It's really easy to add classes to Brick in a way that's minimally disruptive to the existing structure: https://github.com/BrickSchema/Brick/issues/155 fixes the missing classes that we mentioned here

**Comment by gtfierro** [comment]
https://github.com/BrickSchema/Brick/pull/167
