### ISSUE TITLE
Variable_Frequency_Drive and VFD as subclasses of HVAC?

### ISSUE THREAD

**Issue by corymosiman12** [BrickSchema/Brick#156]
There is nothing about these that inherently lend themselves to be part of HVAC.  They can be used in water systems as well.

**Comment by gtfierro** [comment]
Good point. I'll also address this in https://github.com/BrickSchema/Brick/pull/164

**Comment by gtfierro** [comment]
Fixed in https://github.com/BrickSchema/Brick/pull/164
