### ISSUE TITLE
Handle Supply/Discharge Equivalencies

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/Brick#165]
Many of these will want to be equivalent classes; worth a pass through the class hierarchy

**Comment by shreyasnagare** [comment]
@gtfierro Let me know if [this](https://github.com/BrickSchema/Brick/tree/test-similar-constructs) helps.

**Comment by gtfierro** [comment]
Looking into handling supply/discharge equivalencies, it seems appropriate to make sure that the supply/discharge flavors are equivalent in the context of air handling systems.  However, I'm less clear on what the usual terms are for water handling systems: do people just talk about "chilled water supply temp", or is there a need for "chilled water discharge temp" as well? @corymosiman12 would be great to get your perspective on this

**Comment by corymosiman12** [comment]
Hey @gtfierro - I have only heard of supply and return in the context of hydronic systems.  Somebody else would probably know better, but that's my $.02
