### ISSUE TITLE
Additional Inference: Equip types from point types?

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/Brick#171]
For some point classes, it would be nice if Brick could infer the equipment type if a `brick:hasPoint` relationship exists.

For example, if we have an instance `a` of `brick:Exhaust_Fan_Enable_Command`, then we should know that the subject of any `brick:hasPoint` relationship to `a` is a `brick:Exhaust_Fan`.

As equipment-flavored points disappear, this will become less necessary, but there might still be some cases where this is appropriate.

**Comment by support-logicmatter** [comment]
Hi,

Wouldn't isPointOf do the job?
https://www.semanticscholar.org/paper/Brick-%3A-metadata-schema-for-portable-smart-building-Balaji-Bhattacharya/512577b2b1aab6ba0550178172779bb2b745d78a/figure/4

**Comment by gtfierro** [comment]
The `isPointOf` definition currently just says that the subject of the relationship must be a `brick:Point`, but the object can be an `Equipment` or `Location`. This is in line with what I'm proposing, but it's not specific enough for inferring specific `Equipment` classes based on a particular `Point` class.

I'm imagining something along the lines of

```turtle
brick:Exhaust_Fan owl:equivalentClass  (
    a owl:Restriction ;
    owl:hasValue  brick:Exhaust_Fan_Enable_Command ;
    owl:onProperty brick:hasPoint ) .
```

(eliding the rest of the exhaust fan definition for clarity). This says that any entity that has an *instance* of `brick:Exhaust_Fan_Enable_Command` as the object of a `hasPoint` relationship, then that entity is a `brick:Exhaust_Fan`.
