### ISSUE TITLE
Add isSiteOf/hasSite

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/Brick#177]
We prototyped this in earlier papers (e.g. Mortar).

Goal is to include a relationship that captures which individuals in a graph are associated with a Site.

**Comment by shreyasnagare** [comment]
@gtfierro Given that they imply the physical location of an instance, having a more restricted domain/range (`brick:Site` - subclass of `brick:Location`), could they be sub-properties of the location relationships? The implied asymmetric and irreflexive nature would also go well with the site relationships. Does [this](https://github.com/BrickSchema/Brick/compare/add-site-relationships) make sense?

**Comment by gtfierro** [comment]
I like the solution! Encoding that as a subproperty should work great. Feel free to turn that into a PR and we should be able to merge it pretty soon.
