### ISSUE TITLE
Site vs. Building

### ISSUE THREAD

**Issue by corymosiman12** [BrickSchema/Brick#178]
Currently, a `brick:Building` `brick:hasAssociatedTag tag:Site`.  Also, a `brick:Site` `brick:hasAssociatedTag tag:Location, tag:Site`.   This is confusing, since likely a building should also have the associated tag `tag:Location`, which would then make those identical sets of tags to define the same concept. So maybe switch the building tag to have a `tag:Building` instead of a `tag:Site`?

Also, will you provide expected definition for Site?  Is it a physical containment type relationship?  For BuildingSync, we use the [Premises Level](https://bedes.lbl.gov/bedes-online/premises-level) definitions from BEDES, which basically breaks down into:
- Facility > Site > Building > Section > Zone > Space

**Comment by gtfierro** [comment]
Good catch! `Building` should definitely have the `Location` tag as well.

We will include a definition for Site in an upcoming PR. The idea is to have a `Site` be a geographic region which may or many not include one or more buildings; this would be the highest-level grouping of locations in Brick

**Comment by corymosiman12** [comment]
Cool - that aligns with the containment hierarchy we have in BuildingSync (although we have one additional level of 'Facility'), but seems good.
