### ISSUE TITLE
Add entity

### ISSUE THREAD

**Issue by s0301132** [BrickSchema/Brick#179]
Hi @gtfierro!
I'm building a brick model for a building with brick version 1.1, and there are some missing point/ equipments which I want to add:

Energy meter: using chilled water supply/ return temp and flow rate to calculate how many energy(heat) absorb by water.
EC Fan: Electronically Commutated Fan
PA/ PAU: Primary Air/ Primary Air Unit [https://sites.google.com/site/hvacsystemsvariety10/primary-hydronic-convectors](url)

**Comment by gtfierro** [comment]
Hello! Thanks for taking the time to file an issue. I had a couple questions about the concepts you are trying to add.

Energy meter: we are still working on how we want to capture the computational dependencies for this kind of "virtual meter", but for now you can use [Energy Sensor](https://brickschema.org/ontology/1.1/classes/Energy_Sensor) to represent the actual data stream. You can optionally associate this with some sort of [Meter](https://brickschema.org/ontology/1.1/classes/Meter), and then associate the meter with the other equipment/points used to calculate the energy consumption.

EC Fan: usually we organize fans by how they are used (e.g. Exhaust Fan, Return Fan). We've included VFD drivers in Brick before, but maybe we should consider how to better organize these concepts. Maybe we can have a `Driver` or a `Motor` equipment class in Brick and that has `AC`, `DC` and `EC` types? How are you trying to use this proposed class? Are you trying to capture how a fan is driven in addition to its context w/n a larger process?

PA/PAU: is this a distinct concept from AHU? The [link you provided](https://sites.google.com/site/hvacsystemsvariety10/primary-hydronic-convectors) seems to suggest they are the same, but its possible I'm missing something

**Comment by s0301132** [comment]
Hi, thanks for answering me the questions.

For now I can use Energy sensor for virtual meter, may be add a tag to identify those meter as computational dependencies?

For EC fan, now I just use brick:Fan to represent it, there are two types of fan in the building: AC and EC fan so may be add a brick tag to identify those fan?

PAU (Primary Air Unit) is a type of AHU, use to pre-treat the outdoor air before feed to AHU, the definition from EMSD:

> Applications in HVAC systems:
(a) Primary Air handling Unit (PAU)
Conventional Primary air Handling Units (PAUs) usually pre-treat outdoor air at a constant air volume (i.e. CAV). The PAUs supply air to different areas in the building at a constant air flow rate of full load condition, disregard the actual demand. This will waste energy because the PAUs operate at part load instead of full load in most of the time.
Demand control on PAUs using carbon dioxide (CO2) provides unique opportunity to resolve the problem of how to reduce energy costs while optimizing indoor air quality.
CO 2 control is best applied to spaces with variable or intermittent occupancy.

Building Services Research and Information Association (BSRIA) Technical Note (TN) 12/94 suggests that significant energy saving may accrue from the use of CO2 control.

**Comment by gtfierro** [comment]
Let me give some thought as to how to best address the first two items, but I have put PAU on the list of classes to be added soon! You can use `brick:PAU` in your models for now.

**Comment by s0301132** [comment]
Thanks! @gtfierro

**Comment by gtfierro** [comment]
@s0301132 we are in the progress of adding `brick:PAU` (track progress in https://github.com/BrickSchema/Brick/issues/183 until we finish putting the PR together). If you add the following lines to your `ttl` file, you can use `brick:PAU` in your own models:

```ttl
brick:PAU  rdfs:subClassOf  brick:AHU .
```

The question about how to annotate the type of power source of an equipment such as an EC Fan turns out to be a deep one! I don't know that we'll be able to turn something around quickly, but we will definitely be discussing it. For now, you can create subclasses that encode this information; for example, if I have a EC fan installed in a supply configuration, you can create a class like so

```ttl
brick:EC_Supply_Fan rdfs:subClassOf brick:Supply_Fan .
```

and then create instances as if it is a normal Brick class:

```ttl
bldg:ecsf1  a  brick:EC_Supply_Fan .
```

I can't promise that this is the design that we will end up with, but it gives you a way of moving forward and will simplify the task of making your model Brick compliant once we do finish designing the method for annotating properties of equipment.

**Comment by gtfierro** [comment]
Added PAU in #192

**Comment by gtfierro** [comment]
I think that concepts like the EC fan might be better handled by instance metadata such as what is being discussed in https://github.com/BrickSchema/Brick/issues/189. Virtual meters should be part of the discussion at https://github.com/BrickSchema/Brick/issues/188, and I've made a note of it to account for them in the discussion. Closing this issue for now
