### ISSUE TITLE
Adding/Refining More Concepts

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/Brick#183]
The following concepts have been requested from Brick users and/or uncovered in conversations about Brick as not appearing in the class hierarchy yet. This is both a set of directions for @KiithNabaal and also a chance to iterate on documentation for how to add concepts to Brick.

For each of the concepts below, the task is to:

1. determine if the concept belong in Brick or not -- if it is out of scope or a duplicate of a concept Brick already contains, this is worth noting
2. for concepts that should be added to Brick, determine the most appropriate parent class that already exists within Brick. You will find it helpful to browse the Python-defined hierarchies in `bricksrc/`.

    You may find that there is no appropriate parent class, or that the most appropriate parent class is too generic. In this case, it may make sense to include a new class that interposes between the (generic) parent class and the specific concept you want to add. For example, if you are trying to add a `Zone Air Temperature Sensor` and only a `Sensor` concept exists, it may make sense to add a `Temperature Sensor` and even a `Air Temperature Sensor` concept between `Sensor` and `Zone Air Temperature Sensor` (so that it would be a subclass of `Air Temperature Sensor` in this example)
    
    There may also be a family of related classes that are implied by the concept. For example, a `Discharge Fan` would imply that other flavors `Exhaust Fan`, `Return Fan`, `Supply Fan`, etc should also be added
    
   Google, the [ASHRAE dictionary](https://xp20.ashrae.org/terminology/index.php?term=Sensor) and [the BEDES dictionary](https://bedes.lbl.gov/bedes-online) are all helpful resources for helping to determine what each of the classes means. Project Haystack's [new documentation](https://project-haystack.dev/doc/index) has some helpful definitions too.
   
3. add the concepts to the appropriate definition files in `bricksrc/`, following the guidelines in the [CONTRIBUTING](https://github.com/BrickSchema/Brick/blob/master/CONTRIBUTING.md) document. Make sure all the tests pass, make sure to add sensible definitions for the concepts (or point out where you need some help sourcing a good definition).

Points:
- pm10, pm2.6 sensors
- return air temp low/high reset setpoint
- hot water return temp setpoint
- discharge/mixed/return/etc air humidity setpoint
- mixed air humidity sensor
- intake air temp/humidity sensors: associated w/ AHU; make sure to update OAT
  sensor docs to indicate it is *not* intake air
- valve position sensor -- status for read-only?
- fan/pump flow relative output? percentage of max speed, proportion of
  currently active units
- hot/chilled water supply temp setpoint
- min/max air/water temp setpoint limit
- mixed air humidity sensor
- exhaust/discharge/zone air dewpoint sensor
- supply air temperature setpoint (equivalent to discharge air temperature setpoint)

Equipment
- electrically commutated fan?
- add pump vfd, fan vfd
- differential pressure bypass valve
- intake/return air filter
- radiators (under terminal unit)
- controller class
- primary air unit (PAU) (https://github.com/BrickSchema/Brick/issues/179#issuecomment-694806073 )

**Comment by KiithNabaal** [comment]
To familiarize myself with these concepts, I am going to start by looking over the ASHRAE and BEDES terminologies (although less so for BEDES since it is 26 pages long). A lot of these things are unclear to me.

Then I will proceed to check for duplicate concepts in Brick and then move on sequentially with the rest of the tasks.

**Comment by KiithNabaal** [comment]
cfc82c8d740b9ce3132ee3f577d9dcc09a7a2ce1 

If you can take a look to make sure I am adding things correctly, and sensibly, that would help a lot. The task seems pretty straight-forward so I think this shouldn't take _too_ much longer.

I will also be sure to commit each concept I add, and then list it as a comment here outlining the reasoning behind how/why I added it.

**Comment by KiithNabaal** [comment]
As per the call with Gabe, we don't need to add electrically commutated fan as equipment _in this issue_.

**Comment by KiithNabaal** [comment]
ea872836d6a260f81c966405dc5cd557fb91d912 has particulate matter sensors added, and CO/CO2 sensors refactored into particulate matter sensor

**Comment by KiithNabaal** [comment]
a1f8c9b75a5ce3bbdfd4146e107e05f589e63f3f - return air temp low/high reset setpoint

**Comment by KiithNabaal** [comment]
ff1d14c15b65bcccbd2fb12bfab8a174c1b1e1b4 - hot water return temp setpoint

**Comment by KiithNabaal** [comment]
9ee93cee8c85bbd4f5afcc24afa76c7c3207cec5  - discharge/mixed/return/etc air humidity setpoint

**Comment by KiithNabaal** [comment]
Something I noticed with the air substances and humidity sensors is that the air substances all have gas, fluid and air tags but the corresponding air sensors only have the air tags. Ex: discharge air substance doesn't have the same tags as the discharge air humidity sensor. Why is this? I could understand perhaps gas not being present, but why not fluid?

**Comment by KiithNabaal** [comment]
88291fcdb8a349d56f6e121cb99b6ce255c886fb - Mixed air humidity sensor

**Comment by KiithNabaal** [comment]
mixed air humidity sensor is listed twice for points - was something else intended?

**Comment by gtfierro** [comment]
@KiithNabaal substances and points have different sets of tags to differentiate them as concepts. `Discharge Air` as a concept has the `Fluid`, `Gas` tags because it is a substance. `Discharge Air Temperature Sensor` has the `Temperature` and `Sensor` tags because it is a sensor that is measuring the temperature quantity

**Comment by gtfierro** [comment]
@KiithNabaal regarding mixed air humidity sensor, just make sure it has sensible siblings (e.g. discharge air humidity sensor, etc)

**Comment by KiithNabaal** [comment]
@gtfierro What was the line we had added to the Makefile to ignore things like output.ttl if you remember? At one point earlier in the week I did a hard reset when I was trying to debug, but forgot to keep that portion of the code...

**Comment by gtfierro** [comment]
I don't think we added anything to remove the ttl file. Instead we added 'definitions.csv' to the dependencies for the 'Brick.ttl' target

**Comment by KiithNabaal** [comment]
92473cb2c824b96406ee07149cb058d7b617c3bc
6e280e872a85eb7f61ad670bc97069651c490d4b

hot/chilled water supply temp setpoint (two commits because I hadn't realized I had changed the setpoints.py file when adding the descriptions.csv dependency)

**Comment by KiithNabaal** [comment]
25179100697f3f8752e757fb24f62b211a502a02 - exhaust/discharge/zone air dewpoint sensor

**Comment by KiithNabaal** [comment]
32c4e66c8c4ba863ca847288ee012f2febfeaf8d - supply air temperature setpoint (equivalent to discharge air temperature setpoint)

**Comment by KiithNabaal** [comment]
a4392f7dddd78af55558eaa498481063e805c72f - add pump vfd, fan vfd

**Comment by KiithNabaal** [comment]
todo for points:

- intake air temp/humidity sensors: associated w/ AHU; make sure to update OAT
sensor docs to indicate it is not intake air
- valve position sensor -- status for read-only?
- fan/pump flow relative output? percentage of max speed, proportion of
currently active units
- min/max air/water temp setpoint limit (this one I should be able to add, but the other ones I will need clarification on)

**Comment by KiithNabaal** [comment]
ed855907121242049a714db47d496fb4e9073e3c - differential pressure bypass valve

**Comment by KiithNabaal** [comment]
105ad27418cbb6c4a0a5cbf44e2c63fd33e44d8c - intake/return air filter

**Comment by KiithNabaal** [comment]
7b75090d2908e6d1549097b8864ec51435bb2956 - radiators

**Comment by KiithNabaal** [comment]
fc9d3df0c7f41265b99ded2151978303c3b728fa - Added PAU

**Comment by KiithNabaal** [comment]
Hey @gtfierro , I have a few questions on the last sensors:

- _intake air temp/humidity sensors: associated w/ AHU; make sure to update OAT
sensor docs to indicate it is not intake air_ What are the OAT sensor docs?

- _valve position sensor -- status for read-only?_ Can you elaborate on "status for read only"?

- _fan/pump flow relative output? percentage of max speed, proportion of
currently active units_ Can you elaborate more on this? Is relative output something we are unsure if it should be added?

Thanks!

**Comment by gtfierro** [comment]
Hi!

The OAT Sensor docs are the definitions in `definitions.csv`. Thinking about this again, I think we should have `intake air temp sensor` as a subclass of `outside air temp sensor`, with the definition pointing out that an intake air temp sensor is measuring air at the interface between the building and the outside.

You can ignore the `valve position sensor` for now....I'll try to dig up my notes on what I meant by that. You can also ignore the relative outputs for fan/pump: this is a longer discussion about the expected ranges of certain kinds of points.

**Comment by KiithNabaal** [comment]
c4ab3fdb92b2b54f56c7fbaeb20d3370e1830204 - intake air temp sensor

**Comment by KiithNabaal** [comment]
beff1a7ae61bdbff1677efd7653404210cd3861d - Min/Max setpoints for air and water temperature

**Comment by KiithNabaal** [comment]
@gtfierro 

Hey Gabe!

I am trying to add the controller class:

define_classes(controller_subclasses, BRICK.Controller)

When Brick is generated, it looks like BRICK.Controller is not created as an OWL Class in the test.ttl file, and I am getting an error in test_subclasses in test_class_structure because the SPARQL query is returning Brick#Controller. I tried looking at other classes to see if I was missing something, but I think I have everything needed. The define_classes method seems like it should be making this association, so I am not sure what I am doing wrong.

Can you check my commit at 34367ebbfad0766f46b440067ea19894507341e9 to see what I am doing wrong? Thanks!

**Comment by gtfierro** [comment]
It looks like `Controller` isn't actually declared as a root class or as a subclass of an existing class; using it as the second argument in `define_classes` isn't sufficient. You can see when we use `define_classes(<dictionary>, <parent class>)` in `generate_brick.py`, the `<parent class>` is already defined in the class structure (e.g. look at https://github.com/BrickSchema/Brick/blob/master/generate_brick.py#L415 and https://github.com/BrickSchema/Brick/blob/master/bricksrc/equipment.py#L7)

Go ahead and define a base `Controller` class for now but I think this is something we should discuss in the meeting. Would be good to get some external opinions on useful ways of modelling controllers.

Also make sure you are not committing `output.ttl`, `input.ttl`, or other generated files produced by the testing process. These should probably be added to `.gitignore`, but in general if they don't appear in the main branch (https://github.com/BrickSchema/Brick) then they shouldn't be added.

**Comment by KiithNabaal** [comment]
Hey @gtfierro !

So I refactored the code to include the Controller parent class as a tag in the dictionary in equipment.py. I am past the original error, but am now getting an error indicating a loop in the hierarchy. Since we currently don't know what we want to do with Controllers, should we worry about it for this issue? If not, I can create a pull request and merge if everything looks good.

Would you have time tomorrow to go over how to properly add a new class to Brick? I did see the instructions in the contributing doc, but I think it might be incomplete.

Thanks!

**Comment by gtfierro** [comment]
Sure! I've got time 12-5pm EST; send me a calendar invite and we can go through it. Can you push your latest code so I can take a look as well?

**Comment by KiithNabaal** [comment]
Thanks a lot! Would 3:30 pm EST be fine?

Here is the latest commit: 
2d551e5b2cedc9ade41831e287d1ac439a6a651e

**Comment by gtfierro** [comment]
Yep! That works fine

**Comment by gtfierro** [comment]
Fixed in #192
