### ISSUE TITLE
Location Modeling

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/Brick#190]
This has a few main parts:

1) ensure that the mapping with BOT is sensible and up to date with the Brick v1.1 locations
2) produce documentation outlining idiomatic use of Brick v1.1 location classes 
3) decide how to attach "use cases" to locations in the Brick model, e.g. classroom, laboratory, office, etc. There are some existing location use cases in some ASHRAE standards that we can use to bootstrap this

**Comment by gtfierro** [comment]
This topic was discussed during the Brick dev meeting today, and currently we are moving forward with a design that uses OWL classes to denote different types of spaces (categorized by use). Multiuse rooms are modelled by having a Space instance have multiple Space types. We should hopefully have a prototype soon

**Comment by epaulson** [comment]
We put together some possible class extensions for 1.2 that map to the top-level classes of Brick 1.1. It is fairly extensive but only augments what's already there in 1.1. (Well, we think we should bring back 'city' from 1.0.3.)

We can convert this into Python and open a pull request if that would be easier to review, or we can work on this Markdown version and then translate it to Python for an actual PR when we're satisfied with the hierarchy.

For now it's all single inheritance but I think it's all compatible with the plan we discussed of giving a space instance multiple space types to work with multi-use.  

* [**Location** (1.1)](https://brickschema.org/ontology/1.1/classes/Location) 
  * [**Building** (1.1)](https://brickschema.org/ontology/1.1/classes/Building) 
    * Parking_Structure (new) - 
  * [City (1.0.3)](https://brickschema.org/ontology/1.0.3/classes/City) 
  * [**Floor** (1.1)](https://brickschema.org/ontology/1.1/classes/Floor) 
    * [**Basement** (1.1)](https://brickschema.org/ontology/1.1/classes/Basement) 
    * [**Roof** (1.1)](https://brickschema.org/ontology/1.1/classes/Rooftop)
    * Parking_Level (new) - 
  * Location_Portfolio (new) -  - describes a collection of locations, especially Sites that could describe the set of sites belonging to an organization for example
  * Outdoor_Area (new) - 
    * Bench_Space (new) -  - specific to play areas in stadium, an area for participants and referees by the side of the field of play
    * Concourse (new) -  - large outdoor public area usually around a public building
    * Field_Of_Play (new) -  - e.g. a soccer pitch
    * Information_Area (new) -  - e.g. a information kiosk or booth where visitors would look for information
  * [**Outside** (1.1)](https://brickschema.org/ontology/1.1/classes/Outside) 
  * Region (new) -  
  * [**Site** (1.1)](https://brickschema.org/ontology/1.1/classes/Site) 
  * [**Space** (1.1)](https://brickschema.org/ontology/1.1/classes/Space) 
    * Common_Space (new) - 
      * Auditorium (new) - 
      * Cafeteria (new) - 
      * Hallway (new) - 
      * Lobby (new) - 
        * Employee_Entrance_Lobby (new) -  - open space area near employee entrance-uncommon
        * Visitor_Lobby (new) -  - open space/waiting area near main entrance mainly for visitors
      * Lounge (new) - 
        * Majlis (new) - 
    * Entrance (new) -  - space marked as entrance for a building 
    * Gate_House (new) -  - the security gate house monitoring the entrance to a campus (a set of related buildings)
    * Media_Hot_Desk (new) -  - a non-enclosed space that may be used by media (tv/radio)
    * Parking_Space (new) - 
    * [**Room** (1.1)](https://brickschema.org/ontology/1.1/classes/Room) 
      * Ablutions_Room (new) -  - a space for washing up before/after prayers
      * Breakroom (new) -  - a room for employees for snack/food or a break
      * Broadcast_Room (new) -  - a room for organizing Media broadcasts 
      * Communications_Room (new) -  - a room for communication and broadcasting equipment, e.g. at a stadium or a public event place
      * Conference_Room (new) - 
      * Control_Room (new) - 
      * Copy_Room (new) -  - also sometimes referred to as Print Room,  a space where copiers, printers, are located and/or general printing services are available
      * Electrical_Room (new) - 
        * Battery_Room (new) -  - a room for large scale electrical energy storage
        * Generator_Room (new) - 
      * Equipment_Room (new) -  - a room where complicated telecommunications equipment that serves the entire building is stored
      * Exercise_Room (new) -  - an indoor room for warmup / exercise
      * Food_Service_Room (new) -  - food service, e.g. restaurant or cafe or concession
        * Concession (new) -  - a room/stand for usually fast food service
      * Hospitality_Box (new) - 
      * Janitor_Room (new) -  - a maintenance room
      * Kitchen (new) - 
      * [**Laboratory** (1.1)](https://brickschema.org/ontology/1.1/classes/Laboratory) 
        * [**Cold_Box** (1.1)](https://brickschema.org/ontology/1.1/classes/Cold_Box) 
        * [**Environment_Box** (1.1)](https://brickschema.org/ontology/1.1/classes/Environment_Box) 
        * [**Freezer** (1.1)](https://brickschema.org/ontology/1.1/classes/Freezer) 
        * [**Hot_Box** (1.1)](https://brickschema.org/ontology/1.1/classes/Hot_Box) 
      * Library (new) - 
      * Loading_Dock (new) -  - can also be referred to a Delivery Area
      * Mail_Room (new) - 
      * Massage_Room (new) -  - usually adjunct to an athletic/training/medical facility
      * Mechanical_Room (new) -  - also known as Plant Room, a location where HVAC and other building equipments would be located (in real life could be a room, floor, building)
        * Pump_Room (new) - 
      * Media_Production_Room (new) -  - room for tv/radio/broadcast media production, e.g. at a stadium or a public event place
      * Medical_Room (new) - 
        * First_Aid_Room (new) -  - or Nurses' Room
      * Office (new) - 
        * Cubicle (new) - 
        * Enclosed_Office (new) - 
          * Private_Office (new) - 
          * Shared_Office (new) - 
          * Team_Room (new) - 
        * Open_Office (new) - 
      * Plumbing_Room (new) -  - hosting main plumbing distribution and controls
      * Prayer_Room (new) - 
      * Reception (new) - 
      * Restroom (new) - 
      * Retail_Room (new) -  - a space set aside for Retail in a larger establishment, e.g. a gift shop in a hospital
      * Security_Service_Room (new) -  - rooms designated for security service operations
        * Detention_Room (new) -  - a holding place
      * [**Server_Room** (1.1)](https://brickschema.org/ontology/1.1/classes/Server_Room) 
      * Shower (new) -  - usually adjunct to an athletic/training facility
      * Sports_Service_Room (new) -  - servicing sporting activities
      * Storage_Room (new) - 
        * Hazardous_Materials_Storage (new) - 
      * Switch_Room (new) - 
      * TETRA_Room (new) - 
      * Transformer_Room (new) - 
      * Wardrobe (new) - 
      * Waste_Storage (new) -  - exclusive area where waste and recyclables are stored, also called Waste Room
      * Workshop (new) - 
    * Ticketing_Booth (new) - 
    * Tunnel (new) - 
    * Vertical_Space (new) - 
      * Elevator_Space (new) - 
      * Riser (new) - 
      * Staircase (new) - 
    * Water_Tank (new) - 
  * [**Wing** (1.1)](https://brickschema.org/ontology/1.1/classes/Wing) 
  * [**Zone** (1.1)](https://brickschema.org/ontology/1.1/classes/Zone) 
    * Energy_Zone (new) - 
    * [**Fire_Zone** (1.1)](https://brickschema.org/ontology/1.1/classes/Fire_Zone) 
    * [**HVAC_Zone** (1.1)](https://brickschema.org/ontology/1.1/classes/HVAC_Zone)
    * [**Lighting_Zone** (1.1)](https://brickschema.org/ontology/1.1/classes/Lighting_Zone) 
    * Parking_Zone (new) -

**Comment by epaulson** [comment]
We've also collected some of our research here: https://docs.google.com/spreadsheets/d/11_50kLtzwYYX60x074usBqKEc0iPbxQncdfGlViE_bo/edit?usp=sharing

**Comment by epaulson** [comment]
Some early feedback:
- We need to complete definitions for each class
- Consider adding an intermediate class in room to consolidate some of the media spaces
- Switch_room might be better as 'Network_room' or maybe have subclasses like 'IDF' and 'MDF'
- What's the use case for 'parking_zone'

**Comment by david-waterworth** [comment]
One thing we often encounter is what we call a "site" often contains multiple plant rooms - each plant room contains chilled water plant which supplies chilled water to a section of the site - so there may be 3 plant rooms each of which supplies ~1/3rd of the AHU's. 

A section may be a building, or a wing, or it may be an extension of the existing space.

**Comment by corymosiman12** [comment]
Not sure if this is getting into v1.2, but wanted to provide some thoughts.

Regarding more specific types of spaces / facilities:
- ASHRAE 62.1 uses occupancy classifications (categories, space types, w.e.) that are specific to different facility types for calculating ventilation requirements
-  ASHRAE 90.1 uses occupancy classifications, some generic, some specific to facility types, for defining LPD requirements
- The above set of enumerated values do not necessarily overlap or map 1:1
- This gets slightly more confusing because these occupancy classifications change based on code cycles
- The same thing arises for standardized building type definitions. There's CBECS https://www.eia.gov/consumption/commercial/building-type-definitions.php
- There's NAICS building types

All that to say...I think that space type / building type classifications should be entity properties (similar to the `hasBuildingPrimaryFunction`), and should include some metadata about from what standard the classifcation came from (62.1, 90.1, etc.) and potentially which code cycle. Andrew Parker just updated me on the fact that ASHRAE 229p is planning on doing something like:
Space
- ventilation_space_type = Office (something from 62.1 list)
- lighting_space_type = Open Office (something from the 90.1 list)

I'lll propose a few options:
```turtle
ex:space a brick:Space ;
    brick:hasSpaceType [
        :classificationType "Ventilation" ;
        :standard "ASHRAE 62.1" ;
        :standardYear 2019 ;
        :classification "Office" ;
    ] ;
    brick:hasSpaceType [
        :classificationType "Lighting" ;
        :standard "ASHRAE 90.1" ;
        :standardYear 2016 ;
        :classification "Open Office" ;
    ] .
# OR
ex:space a brick:Space ;
    brick:hasVentilationSpaceType "Office" ;
    brick:hasLightingSpaceType "Open Office" .
```

There's also the possiblity of defining a 'standard' concept, which might include design information, and then a building could point to a standard in some fashion.

**Comment by epaulson** [comment]
We are hoping to get this into 1.2 - we talked about a property based approach back in the fall but had settled on a class hierarchy, but we hadn't really settled on how we were going to expand properties in 1.2 when we had that discussion. 

For 1.2 we're still going to go with adding a set of classes for locations, but exploring properties is worth revisiting - we can add some reasoner rules about how to map between classes and properties, and I think the properties opens up some good interop options that can be reasonably transparent to users.

**Comment by jbkoh** [comment]
@corymosiman12  What's the difference between different space types? Are offices for ventilation different from the ones for lighting?

Besides that, different standards would better be handled by name spaces instead of materializing all the meta-properties like Year and standard name.

**Comment by corymosiman12** [comment]
The main difference for space types is from a design perspective. ASHRAE 62.1 prescribes certain design requirements for ventilation based on the space type. ASHRAE 90.1 prescribes maximum lighting power densities (W/sf) based on the intended space type. A quick snap shot shows as follows:

ASHRAE 90.1 LPD Examples:
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/28991233/108433781-874fd300-7214-11eb-801f-47d0ce4251b6.png)

ASHRAE 62.1 Ventilation Examples:
![image](https://user-images.githubusercontent.com/28991233/108434076-0cd38300-7215-11eb-963c-7d7c32c36727.png)

**Comment by jbkoh** [comment]
@corymosiman12 Thanks for the explanation! It sounds like space types drive the requirements for different systems but not the other way around. If the space type is office, HVAC should be configured as X and Lighting should be configured as Y, meaning that space types should be agnostic from such operation standards. Please correct me if I'm not following correctly.

**Comment by jbkoh** [comment]
Given release v1.2, shall we close this Issue?

**Comment by corymosiman12** [comment]
I think that's correct, except the consideration is that the _enumerations for space types_ are different and therefore define different requirement types.
