### ISSUE TITLE
Units Documentation

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/Brick#191]
Need to provide some good documentation on how units work in Brick, with examples of usage and some basic integration of the units data model with supporting tools like py-brickschema.

**Comment by gtfierro** [comment]
Working on some documentation, hosting the beta documents [here](https://beta-docs.brickschema.org/intro.html). @epaulson @jbkoh @shreyasnagare let me know what you think so far (the units documentation is specifically [here](https://beta-docs.brickschema.org/brick/timeseries.html)).

I'm working on making the code snippets executable so that the documentation can be interactive. Imagine if I mention a SPARQL query in the documentation (i.e. "here's how to get valid units for a temperature sensor" or "here's how to find all downstream equipment from a given AHU") and being able to hit a button and see the results live, along with the Python code that would produce similar results on your own model.

**Comment by gtfierro** [comment]
@shreyasnagare what do you think is the best way to get this integrated with the current website? The Jupyter book itself is a set of static files that can be easily served; it does need to be "compiled" by running a `jupyter book build` command. I like the idea of hosting it on the docs.brickschema.org subdomain so that it can remain stylistically separate, but we would need to link to it from the main Brick site. Maybe a "Docs" link on the top navbar that brings you directly to docs.brickschema.org? What do you think?

**Comment by gtfierro** [comment]
I've pushed the documentation source to https://github.com/BrickSchema/docs

**Comment by epaulson** [comment]
I like adding 'Docs' to the top of the navbar, probably after "Getting Started" and before 'Resources. If we're worried about running out of navbar space, maybe we fold 'Blog' under "Community" or "Getting Started"

**Comment by gtfierro** [comment]
I like the suggestion! I added Docs before Get Started for now because I couldn't figure out how to get the autogenerated navbar to interpose an external link, but once https://github.com/BrickSchema/brick-website/pull/91 is fixed and merged then we should be good to go.

**Comment by shreyasnagare** [comment]
Merged. The changes are [live](https://brickschema.org/).

**Comment by gtfierro** [comment]
Thanks all!
