### ISSUE TITLE
Thermal Energy Meter

### ISSUE THREAD

**Issue by david-waterworth** [BrickSchema/Brick#199]
There's a Thermal_Power_Sensor in the Point taxonomy but I don't see a Thermal_Power_Meter in the Equipment taxonomy. They're the same concept but the former can be used on an Equipment that reports thermal power as a telemetry point (i.e. a chiller with a BACnet controller or HLI), the latter is required in cases where a stand-alone thermal power meter has been installed, in the same way an electrical sub-meter would be used to measure the power consumption of equipment which doesn't have its own meter built-in.

**Comment by gtfierro** [comment]
Thanks for the catch! I should be able to add this in a future PR

**Comment by gtfierro** [comment]
Addressed in v1.2.0 release
