### ISSUE TITLE
Point Request(s)

### ISSUE THREAD

**Issue by kkellyqq** [BrickSchema/Brick#205]
Could we add:

- `Mixed Air Damper` with `Damper` as parent equipment Class. Definition would be: A damper that modulates the flow of the mixed outside and return air streams. _This is a standard component in an AHU that is not captured anywhere else in Brick._
- `Condenser Water Valve` with a `Water Valve` as the parent equipment class. Definition would be: A valve that modulates the flow of condenser water. _To be consistent, if we are modeling Chilled Water Valves, we want to model Condenser Water Valves the same way._
- `Fresh Air Fan` with a `Fan` as the parent equipment class. Definition would be: Fan moving fresh air -- air that is supplied into the building from the outdoors. _To be consistent, if we are modeling Exhaust Fans, we want to model Fresh Air Fans the same way._
- `Zone Air Temperature Cooling Setpoint` with `Zone Air Temperature Setpoint` & `Cooling Temperature Setpoint` as a Parent Equipment Classes. 
- `Zone Air Temperature Heating Setpoint` with `Zone Air Temperature Setpoint` & `Heating Temperature Setpoint` as a Parent Equipment Classes. 
- `Return Air Temperature Setpoint` with `Air Temperature Setpoint` as a parent equipment class. _Many times single zone AHUs are missing zone air temperature sensors, so they end up using the Return Air Temp sensor as the control point to approximate the zone temperature._
- `Occupied Air Temperature Setpoint` with `Air Temperature Setpoint` as the parent point class. Also, to align with `Unoccupied Air Temperature Setpoint` structure, we need to add `Occupied Air Temperature Cooling Setpoint` and `Occupied Air Temperature Heating Setpoint` with `Occupied Air Temperature Setpoint` as the parent point class. _Though, to be honest, we may want to create Effective, Unoccupied, & Occupied Air Temp Setpoints for Discharge Air, Return Air, Zone Air, & Supply Air._ This would look like: `Effective Discharge Air Temperature Setpoint`,`Unoccupied Discharge Air Temperature Setpoint`, `Occupied Discharge Air Temperature Setpoint`, `Effective Return Air Temperature Setpoint`,  `Unoccupied Return Air Temperature Setpoint`, `Occupied Return Air Temperature Setpoint`,`Effective Zone Air Temperature Setpoint`,  `Unoccupied Zone Air Temperature Setpoint`, `Occupied Zone Air Temperature Setpoint`, `Effective Supply Air Temperature Setpoint`,`Unoccupied Supply Air Temperature Setpoint`, `Occupied Supply Air Temperature Setpoint`

I will update this ticket when/if more missing classes are identified in the coming week or so.

**Comment by gtfierro** [comment]
Thanks for the asks! I think these all fit cleanly within the existing structure and I should be able to get to this next week.

**Comment by gtfierro** [comment]
Addressed in v1.2.0 release
