### ISSUE TITLE
Measurements for air quality analysis

### ISSUE THREAD

**Issue by DanieleAntonucci** [BrickSchema/Brick#228]
There are some parameters that we measure to evaluate the air quality.  Some of them have been already implemented few days ago. 

**Parameter:                        Unit**
Carbon monoxide :              [ppm]
Formaldehyde :                     [ppm]
VOC or tVOC :                       [ppb] or [ppm] or [ug/m3]
Particulate_matter_1 :          [ug/m3]
Particulate_matter_2.5 :      [ug/m3]
Particulate_matter_10 :        [ug/m3]
Ozone :                                  [ppm]
Nitrogen_dioxide :                [ppm]

Thanks

Daniele

**Comment by epaulson** [comment]
We might want to add radon and methane?

Also the ASHRAE COVID air quality resources might be good to take a look over but that might be better in a separate issue
https://www.ashrae.org/file%20library/technical%20resources/covid-19/ashrae-building-readiness.pdf
