### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'extensions/brick_extension_shacl_tag_inference.ttl'

### ISSUE THREAD

**Issue by jbulow** [BrickSchema/Brick#232]
On branch v1.2-release when running `python generate_brick.py`:

```
Traceback (most recent call last):
  File "/big/Brick/generate_brick.py", line 633, in <module>
    with open(f"extensions/brick_extension_{name}.ttl", "wb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'extensions/brick_extension_shacl_tag_inference.ttl'
```

**Comment by gtfierro** [comment]
I think this occurs when the `extensions/` directory doesn't exist. I believe I added a rule to the Makefile that should ensure that the directory is created if it doesn't exist, so if you run `make`, the build should complete correctly. Can you verify that this addresses the issue?

**Comment by jbulow** [comment]
Yes, running make solved the issue.  Thanks!

I was just following the documentation when building the brick ontology from source, so it's just a documentaiton bug.

**Comment by gtfierro** [comment]
Great! Glad that its working

There's also a `README` in the `extensions/` directory now, so running `generate_brick.py` by itself should now not depend on going through the Makefile. Can you point to which piece of documentation you were following so I can make sure to mention the Makefile?

**Comment by jbulow** [comment]
It was the end of [CONTRIBUTING.md](https://github.com/BrickSchema/Brick/blob/master/CONTRIBUTING.md
)

**Comment by gtfierro** [comment]
I added some documentation for this in #214, so hopefully this should be addressed for future developers.
