### ISSUE TITLE
the nightly build fails, every other day

### ISSUE THREAD

**Issue by epaulson** [BrickSchema/Brick#238]
These are the best sort of bugs!

The nightly build fails every other day/fails on every even day. 

I wonder if it's the plus sign in the Brick+extensions.ttl filename is confusing things, like the plus sign gets escaped wrong in some places, and the step that goes to deletes Brick.ttl gets both Brick.ttl and Brick+extensions.ttl, so on some days the upload succeeds because the old version isn't there but then it fails the next day because the file is there - but is cleaned up again soon and we get into this alternating state.

I think this might be a bug in the release action plugin we're using but I'm not sure yet.

How often do nightly builds get purged/where is that configured?

**Comment by gtfierro** [comment]
Should be fixed in https://github.com/BrickSchema/Brick/pull/241 . Fix was tested on https://github.com/gtfierro/reasonable/releases. I can reopen this issue if we continue to hit problems.
