### ISSUE TITLE
Adding more metadata in Brick Ontology

### ISSUE THREAD

**Issue by gatemezing** [BrickSchema/Brick#242]
Hi guys, I just found this awesome ontology. I want to add it into [LOV](https://lov.linkeddata.es/) so that people can easily reuse it in the LOD space. However, I suggest adding more metadata in the ontology, such as the first issued date, modified date each time there is a new release, etc. Something along the following:

> brick: a owl:Ontology ;
 rdfs:label "Brick" ;
	dcterms:description "A uniform metadata schema for buildings";
    dcterms:creator ( [ a sdo:Person ;
                sdo:email "gtfierro@cs.berkeley.edu" ;
                sdo:name "Gabe Fierro" ] [ a sdo:Person ;
                sdo:email "jbkoh@eng.ucsd.edu" ;
                sdo:name "Jason Koh" ] ) ;
    dcterms:license <https://github.com/BrickSchema/brick/blob/master/LICENSE> ;
    dcterms:version "1.2.0" ;
	dcterms:issued "2020-12-20" ; #first issued date
	dcterms:modified "2021-02-21" ; # your last modified date
	dcterms:publisher <https://brickschema.org/consortium> ;
    rdfs:isDefinedBy <https://brickschema.org/schema/1.2/Brick> ;
    rdfs:seeAlso <https://brickschema.org> .

**Comment by gtfierro** [comment]
Hello @gatemezing! Thanks for the suggestion to add more metadata to Brick . I've just filed #245 which adds the items that you mentioned. The PR will amend the ontology definition to the following:

```ttl
<https://brickschema.org/schema/1.2/Brick> a owl:Ontology ;
    rdfs:label "Brick" ;
    dcterms:creator ( [ a sdo:Person ;
                sdo:email "gtfierro@cs.berkeley.edu" ;
                sdo:name "Gabe Fierro" ] [ a sdo:Person ;
                sdo:email "jbkoh@eng.ucsd.edu" ;
                sdo:name "Jason Koh" ] ) ;
    dcterms:issued "2016-11" ;
    dcterms:license <https://github.com/BrickSchema/brick/blob/master/LICENSE> ;
    dcterms:modified "2021-03-23" ;
    dcterms:publisher [ a sdo:Consortium ;
            sdo:legalName "Brick Consortium, Inc" ;
            sdo:sameAs <https://brickschema.org/consortium/> ] ;
    rdfs:isDefinedBy <https://brickschema.org/schema/1.2/Brick> ;
    rdfs:seeAlso <https://brickschema.org> ;
    owl:versionInfo "1.2.0" .
```

Can you verify that this matches what you would expect? Thanks!
