### ISSUE TITLE
No dcterms:version in Dublin Core namespace

### ISSUE THREAD

**Issue by gatemezing** [BrickSchema/Brick#243]
Hello, 
Also, I found a small typo? in the ontology file. The property `dcterms:version` seems not present in the Dublin Core namespace.  I suggest the use of `owl:versionInfo` because the range of the`dcterms:hasVersion` seems not suitable as well. HTH.

**Comment by gtfierro** [comment]
Thanks for catching that! Don't know how we ended up with something that doesn't even exist in the ontology. #245 should address these issues
