### ISSUE TITLE
Description of hasPoint

### ISSUE THREAD

**Issue by david-waterworth** [BrickSchema/Brick#244]
The description element of "hasPoint" is a bit misleading ("The subject has a digital/analog input/output point given by the object") since points can be AV/BV's or other. The description from https://docs.brickschema.org/brick/relationships.html seems more appropriate "the subject has a source of telemetry identified by object".

**Comment by gtfierro** [comment]
Thanks for the feedback! I agree that the other definition is a bit more clear, but it is still made in the context of the full document. I'll make a note to revisit the description of that relationship soon

**Comment by gtfierro** [comment]
@david-waterworth can you take a look at #251 when you get a chance and let me know if the updated definitions work for you?
