### ISSUE TITLE
Additional Fans and Fan-Related Equipment

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/Brick#272]
As identified by @david-waterworth

- FVAV (fan-assisted VAV): essentially any VAV with a fan in it. Maybe a SHACL shape can infer FVAV for VAVs that hasPart Fan
- Extractor Fans: multiple types
  - Smoke Extractor Fan
  - Garbage Exhaust Fan
  - Kitchen Exhaust Fans
  - Carpark Exhaust Fans

Issues:
- Does Brick just need one kind of Extractor Fan, which is then "fedBy" the different kinds of rooms?

**Comment by gtfierro** [comment]
@david-waterworth is Exhaust Fan sufficient to capture the idea of Extractor Fans? Or are they distinct concepts? Maybe Extractor Fan is a subclass of Exhaust Fan?

Additionally, how do you feel about having just the one kind of Exhaust/Extractor Fan that is "fedBy" the different kinds of spaces?

**Comment by david-waterworth** [comment]
Hi @gtfierro 

As far as I can see exhaust and extractor are used interchangeably to represent something that removes pollutants and contaminants from inside to outside. I think you could model them all as subclasses of Exhaust Fan (i.e. don't mention Extractor at all) as that seems more common.

https://ncc.abcb.gov.au/ncc-online/NCC/2016-A1/NCC-2016-Volume-One/Section-E-Services-And-Equipment/Specification-E22B-Smoke-Exhaust-Systems/1-Scope?inlineLink=%7B90E898C2-491A-45BC-8B52-508E083B13F7%7D

The advantage of modelling them separately is you then don't have to model the spaces if you don't need to - i.e. If you wanted to model a KEF as an EF fedBy Kitchen you'd have to explicitly add a Kitchen space to the model.

I think if anything you'd probably want a `contaminant` tag which indicates which contaminant the EF is exhausting (smoke, CO, odour(?), not sure how to describe what a KEF exhausts) instead?

**Comment by gtfierro** [comment]
We can address an entity property for "contaminant" possibly at a later date. The design decision to include the entity with which a point or equip is associated (e.g. modeling the Kitchen for a Kitchen exhaust fan) is not going to be resolved here --- this is part of a larger discussion. Closing this issue for now. Thanks @david-waterworth for your feedback!
