### ISSUE TITLE
RFC: Add Electrical Domain

### ISSUE THREAD

**Issue by bbalaji-ucsd** [BrickSchema/Brick#28]
We need to add the following as part of Equipment class. The hierarchy can be part of Electrical System, just like a separate hierarchy for HVAC, Lighting System, etc.

- Power meters
… We need to have a notion of which areas of a building does the power meter cover. 
... Points: Voltage, Current, Power, Energy

- Circuit Panel
... Knowing where they are located and what areas they cover is useful for fault diagnosis and general maintenance.

- Fuses
... Knowing which circuit panel they are part of is useful for fault diagnosis

- Solar Panels
… location and points to indicate power generation characteristics
... Leaving points out until we have a concrete example

- Energy Storage
… Location, current charge levels, capacity, charging status
... Leaving points out until we have a concrete example

The relationships we will need:
PowerMeter isSubClassOf Meter
PowerMeter covers Location_Entity

PowerMeter can have the Points: Voltage, Current, Electrical Power, Electrical Energy
Note 1: Need the word "Electrical" to distinguish it from "Thermal"
Note 2: May need to add "Sensor" to each Point above to be consistent with rest of Brick.

ElectricalSystem isSubClassOf Equipment
CircuitPanel isSubClassOf ElectricalSystem
Fuse isSubClassOf ElectricalSystem
SolarPanel isSubClassOf ElectricalSystem
EnergyStorage isSubClassOf ElectricalSystem

Fuse isPartOf CircuitPanel (read can be part of, will be isPartOf in an instance)
CircuitPanel covers Location_Entity (also for respective instances)

**Comment by blip2** [comment]
I've started further discussion here: https://groups.google.com/forum/#!topic/brickschema/6QvW5kJEmks

**Comment by gtfierro** [comment]
Closing this discussion now for inactivity, but if anyone is interested in investigating how to add more electrical domain concepts to Brick please let me know!
