### ISSUE TITLE
Reference to Brick from LBD

### ISSUE THREAD

**Issue by JoelBender** [BrickSchema/Brick#287]
Please submit a pull request for the W3c Linked Building Data [Ontologies](https://github.com/w3c-lbd-cg/ontologies) page to reference Brick.

**Comment by gtfierro** [comment]
Thanks for the pointer! I submitted https://github.com/w3c-lbd-cg/ontologies/pull/2 this afternoon

**Comment by gtfierro** [comment]
The PR was merged
