### ISSUE TITLE
Use of Luminance

### ISSUE THREAD

**Issue by blip2** [BrickSchema/Brick#29]
Typically lighting systems within buildings are designed, specified and installed based on illuminance levels (measured in lux). The use of luminance for a number of classes (particularly for LightingSystem) while technically still a valid measurement, not actually the correct terminology what what happens in practice.

**Comment by jbkoh** [comment]
In-depth discussion continues at Brick Google Groups. The discussion will be summarized here once it's finalized there:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/brickschema/crnEA450VJ8/ZTdORh1UCAAJ

Any comments and discussions are welcome here too.

**Comment by jbkoh** [comment]
Summary of the discussions so far. 

1. Introduce following TagSets: (I have aligned the style to other existing Brick tagsets.)
Equipment | Lighting
Equipment>Lighting | Luminaire
Equipment>Lighting>Luminaire | Maintained Emergency Luminaire
Equipment>Lighting>Luminaire | Nonmaintained Emergency Luminaire
Equipment>Lighting | Luminaire Driver
Point>Sensor | Absence Sensor
Point>Sensor | Illuminance Sensor
Point>Sensor > Illuminance Sensor | Photocell Illuminance Sensor

2. Introduce following TagSets (need discussions for proper hierarchy.)
Equipment> Switch
Equipment> Lighting | Dimmer
Equipment> Control Module
Equipment | Touchpanel

3. Possible relationship
Luminaire feeds (or feedsLight) Lighting_Zone

4. Do we need Luminance Sensor? (different from Illuminance Sensor)

5. Introduce a common concept: Interface
Dimmer, Scene Set, Touch Panel in Lighting Systems,
Thermostat in HVAC.

6. Introduce a common concept: Control Module.
Control Module in Lighting System
NAE or others in HVAC.

**Comment by pisuke** [comment]
I'd like to get this discussion higher in the list of issues to be addressed.
Luminance sensors are not needed (the term is wrong). 
All the rest of changes is appropriate. 
I'm happy to do the changes. What is the appropriate way: fork and do a pull request?

**Comment by gtfierro** [comment]
Yep! @pisuke just fork, make the changes in the `src/` directory to `TagSets.csv`, and then run `build.sh` which will generate the turtle files. Please separate the edits to `TagSets.csv` and the execution of `build.sh` into separate commits (they can be more than 1 commit each, but please don't combine the two steps into a single commit).

Editing `TagSets.csv` is a bit hairy right now, but we're working on fixing that

**Comment by gtfierro** [comment]
Closing this issue for now to reflect the work that has been done on adding Lighting concepts to Brick (not that we're done :)). Please continue this conversation in https://github.com/BrickSchema/Brick/issues/173
