### ISSUE TITLE
brick:PV_Generation_System missing in ontology

### ISSUE THREAD

**Issue by jbulow** [BrickSchema/Brick#290]
`brick:PV_Generation_System` is referenced in the `solar_array.ttl` example. It is not found in the current head-of-tree built ontology.

https://github.com/BrickSchema/Brick/blob/9f6727019a64dfd0e0c407ef517a7ca69ab9fb00/examples/solar_array/solar_array.ttl#L114

**Comment by gtfierro** [comment]
You are absolutely right! It is currently defined in PR https://github.com/BrickSchema/Brick/pull/269, which hasn't been merged yet. I'll try to fix that up today
