### ISSUE TITLE
Add rdfs:label's to all entities

### ISSUE THREAD

**Issue by david-waterworth** [BrickSchema/Brick#304]
A number of schema entities don't have labels, in particular, most of the relationships (`hasPoint`, `hasPart` etc) along with a number of others. Some tools (INCEpTION) only import classes/instances which have an `rdfs:label`. Ideally every concept would have a label. Also the `skos:definition`'s have `@en` suffix but the `rdfs:label`'s don't - perhaps they should?

Some also have duplicates, i.e. 

```
brick:Active_Energy a qudt:QuantityKind,
        brick:Quantity ;
    rdfs:label "Active Energy",
        "Active_Energy" ;
    qudt:applicableUnit unit:KiloW-HR,
        unit:MegaW-HR,
        unit:W-HR ;
    rdfs:isDefinedBy <https://brickschema.org/schema/Brick> ;
    skos:broader brick:Electric_Energy ;
    skos:definition "The integral of the active power over a time interval" .
```

This isn't an exhaustive list, but it appears that they're all qudt:QuantityKind (but the converse isn;t true, not all qudt:QuantityKind's have duplicates).

```
brick:Active_Energy
brick:Alternating_Current_Frequency
brick:Apparent_Energy
brick:CO2_Concentration
brick:CO_Concentration
brick:Current_Angle
brick:Current_Imbalance
brick:Current_Total_Harmonic_Distortion
brick:Flow_Loss

```

**Comment by david-waterworth** [comment]
I think the duplicate labels are caused by the generator automatically creating labels from the IRI

https://github.com/BrickSchema/Brick/blob/cfdded830417160e9c9d7d577357e787f4f3727b/generate_brick.py#L232

But some of the source files explicitly adding one, i.e. 

https://github.com/BrickSchema/Brick/blob/cfdded830417160e9c9d7d577357e787f4f3727b/bricksrc/quantities.py#L425

**Comment by gtfierro** [comment]
@david-waterworth can you take a look at https://gist.github.com/gtfierro/253796937c34e8666f45e2905e46e91a and let me know if that version of Brick works for you? I've generated this from the #307 PR

**Comment by david-waterworth** [comment]
@gtfierro yes that works well in INCEpTION thanks!

**Comment by gtfierro** [comment]
Thanks for confirming, and for your detailed bug report! Closing for now
