### ISSUE TITLE
Some applicable units seem to be missing?

### ISSUE THREAD

**Issue by shreyasnagare** [BrickSchema/Brick#305]
I'm not sure if this was intentional but there are a few applicableUnits missing for some quantities. 

Examples from Brick v1.2.0:
- `brick:Temperature qudt:applicableUnit unit:DEG_F .`  (this one's fixed now)
- `brick:Temperature qudt:applicableUnit unit:DEG_C .`  (missing?)

Question: Shouldn't units applicable to narrow concepts (say brick:Dry_Bulb_Temperature) be applicable to a broader concepts (brick:Temperature) as well?

Also, should there be more members in this SHACL list or is it meant to target only ambient temperatures for power outputs?
```ttl
brick:Temperature a brick:Quantity ;
    rdfs:label "Temperature" ;
    qudt:applicableUnit unit:DEG_F,
        unit:DEG_R,
        unit:K,
        unit:MilliDEG_C,
        unit:PlanckTemperature ;

brick:TemperatureShape a owl:Class,
        sh:NodeShape ;
    sh:property [ a sh:PropertyShape ;
            sh:datatype xsd:double ;
            sh:minCount 1 ;
            sh:path brick:value ],
        [ a sh:PropertyShape ;
            sh:in ( unit:DEG_C unit:DEG_F ) ;
            sh:minCount 1 ;
            sh:path brick:hasUnit ] .
```

**Comment by gtfierro** [comment]
There's a few issues wrapped up in here so I will try to separate them.

The applicableUnit structure in Brick is based on QUDT and the equivalencies between Brick Quantities and QUDT QuantityKinds. In QUDT, CelsiusTemperature is _narrower_ than ThermodynamicTemperature, but Brick Temperature is only connected to ThermodynamicTemperature, hence we don't pick up the Celsius units. I'm not going to debate the choice that QUDT made, but I think the easiest fix is to equate Brick Temperature to CelsiusTemperature, and then pick up the _broader_ quantity kinds and their associated units automatically.

Your first question is about applicableUnits applying _up_ or _down_ the SKOS hierarchy. I'm less convinced this is a good idea. We should see what we can get out of the QUDT hierarchy traversal first

We could definitely add more units to the TemperatureShape.
