### ISSUE TITLE
Clear distinction of delta from their related classes

### ISSUE THREAD

**Issue by jbkoh** [BrickSchema/Brick#330]
In the current design, delta concepts are subsumed by its related classes. E.g., `Water_Differential_Temperature_Sensor` is a subclass of `Water_Temperature_Sensor`. However, even though they are related, they are different. E.g., if a user queries, I would like to know the temperature of water, the query will be asking for getting `Water_Temperature_Sensor`, which incorrectly includes `Water_Differential_Temperature_Sensor` now. They will get totally different values for the same place.

This applies to `Deadband` concepts as well.

Those two should be differentiated all over the place. If I see agreement here, I will create a PR for that.

A side node, CO2_Differential_Sensor should be changed to `Differential_CO2_Sensor` for consistency.

**Comment by gtfierro** [comment]
Definitely agree; I like the idea of putting Differential sensors under their own Sensor subtree. We can do the same for putting Deadband setpoints under their own Setpoint subtree.

**Comment by jbkoh** [comment]
ok will work on a PR.

**Comment by gtfierro** [comment]
Sounds good! Make sure to link the PR to this issue when it is submitted

**Comment by jbkoh** [comment]
closing this one by observing #375
