### ISSUE TITLE
Status vs Sensor for Position/Frequency

### ISSUE THREAD

**Issue by jbkoh** [BrickSchema/Brick#332]
We are currently adopting `Sensor` for positions and frequencies such as `Damper Position Sensor`. We had a brief discussion (and I believe it was discussed in 223P a while ago too) whether they should be `Sensors` or `Statuses` because they are not actually measuring things such properties but instead controller-set variables. I feel we should change them `Status` before too late. Any thoughts? Is it too much breaking?

**Comment by gtfierro** [comment]
They are two separate concepts. It is true that most damper position points are either Commands or Statuses (for r/w and read-only, respectively) that read from the controller's register. However, there are real damper position *sensors* which actually measure the position of the damper (e.g. [this one](https://www.kele.com/actuators-and-dampers/tt-470-series.aspx)) so I think it is important to keep both kinds. I believe the definitions for the respective classes already differentiate between these two scenarios; do you think there is another more effective way we could communicate that information?

**Comment by gtfierro** [comment]
I like this idea. Maybe a term like `brick:seeAlso` or `brick:relevant` rather than "approximate"? I can bring this up at the working group meetings
