### ISSUE TITLE
Need Room Air Temperature & Zone Air Temperature Sensors?

### ISSUE THREAD

**Issue by jbkoh** [BrickSchema/Brick#334]
Zone Temperature Sensor is a commonly used term in HVAC systems. However, its definition is defined by its association with a certain Zone. So it's context is defined by the Zone while the tag in the class barely do anything other than increasing incompatibility across different uses. A representative example is a Room Temperature Sensor.
- If there is an ambient temperature sensor in a room that is a part of an HVAC zone, is it a `Room Air Temperature Sensor` or `Zone Air Temperature Sensor`?
- If the zone consists of only of the room in the above case, what should be the right class?
- If a user is interested in the temperature of the room, should it query for a Room Air Temperature Sensor or Zone Air Temperature Sensor? Otherwise, just Air Temperature Sensor?
- The current definition of Zone Temperature Sensor is "Measures the temperature of air in a zone". Does a Room Temperature Sensor in a Zone measure the temperatuer in the zone or not?

After answering those questions, I realized we should reconsider the usefulness of those classes.

I can think of only a single use case of `Zone Air Temperature Sensor` as a single reference temperature representing the entire zone used by the corresponding control loop. This definition is very specific, which I like and I think can be generally agreeable. This definition is different from the current generic definition.

Thus, I propose two options
1. Remove Zone Air Temperature Sensor and Room Air Temperature Sensor. Otherwise,
2. Change the Zone Air Temperature to be very specific as similar to what I described above and remove Room Air Temperature Sensor.

Brick should be opinionated as much as we can to promote interoperability across different users. Having both classes without clear definitions and use cases will harm the interoperability.

**Comment by gtfierro** [comment]
I like the idea of making the definition Zone Air Temp Sensor more specific to indicate that it is representative of the temperature of the zone. This may be a virtual sensor, produced by some statistical combination of Room Air Temp Sensors, or it may be an actual sensor located somewhere in the zone. Whether a given sensor is considered to be representative of the zone is a decision made by the controller. I support making the definition of Zone Air Temp Sensor more specific, perhaps "A physical or virtual sensor which represents the temperature of an HVAC Zone"?

**Comment by jbkoh** [comment]
I also like the new definition, but it still doesn't solve the problem with its confusion with Room_Air_Temperature_Sensor. If there is a temperature sensor used by a VAV in a room, it is both a Zone_Air_Temperature_Sensor and a Room_Air_Temperature_Sensor. As Brick experts, you and I know an entity can be an instance of multiple classes, but it's a long way to explain properly to all the users, and it'll certainly cause confusions and discrepancy.

**Comment by jbkoh** [comment]
My apologies, Room Air Temperature Sensor doesn't exist. Updating the definition will be sufficient. I will create a PR for this.

**Comment by jbkoh** [comment]
Closing this one by https://github.com/BrickSchema/Brick/pull/374
