### ISSUE TITLE
Swap Supply/Return for Entering/Leaving for water system Points

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/Brick#358]
While the use of supply/return in water systems is not uncommon, the measurement location of a sensor is ambiguous from the use of the word supply/return because these systems involve loops. In the HVAC domain, supply/return are defined with respect to the zone: "supply to the zone" and "return from the zone".

It has been suggested from multiple sources that instead of "condenser water return" and "condenser water supply", we use terms like "leaving condenser water" or "entering condenser water" to clarify that the water being measured is leaving/entering the condenser (respectively).

@wcrd @epaulson do I have this correct?

**Comment by gtfierro** [comment]
(on `v1.3.0` branch)

```python
import brickschema
g = brickschema.Graph().load_file("Brick.ttl")
res = g.query("""SELECT ?point WHERE {
  ?point rdfs:subClassOf+ brick:Sensor .
  ?point brick:hasSubstance/rdfs:subClassOf* brick:Water .
  { ?point brick:hasAssociatedTag tag:Return } UNION { ?point brick:hasAssociatedTag tag:Supply}
}""")
for row in res:
   print(row[0])
```

```
https://brickschema.org/schema/Brick#Chilled_Water_Supply_Flow_Sensor
https://brickschema.org/schema/Brick#Hot_Water_Return_Flow_Sensor
https://brickschema.org/schema/Brick#Hot_Water_Supply_Flow_Sensor
https://brickschema.org/schema/Brick#Return_Water_Flow_Sensor
https://brickschema.org/schema/Brick#Return_Condenser_Water_Flow_Sensor
https://brickschema.org/schema/Brick#Supply_Water_Flow_Sensor
https://brickschema.org/schema/Brick#Supply_Condenser_Water_Flow_Sensor
https://brickschema.org/schema/Brick#Return_Condenser_Water_Temperature_Sensor
https://brickschema.org/schema/Brick#Supply_Condenser_Water_Temperature_Sensor
https://brickschema.org/schema/Brick#Chilled_Water_Supply_Temperature_Sensor
https://brickschema.org/schema/Brick#Return_Water_Temperature_Sensor
https://brickschema.org/schema/Brick#Differential_Supply_Return_Water_Temperature_Sensor
https://brickschema.org/schema/Brick#Differential_Supply_Return_Water_Temperature_Sensor
https://brickschema.org/schema/Brick#Differential_Supply_Return_Water_Temperature_Sensor
https://brickschema.org/schema/Brick#Differential_Supply_Return_Water_Temperature_Sensor
https://brickschema.org/schema/Brick#Hot_Water_Supply_Temperature_Sensor
```

**Comment by fstinner** [comment]
@gtfierro Good idea. I've had the same thoughts with all water-based systems. Depending on the location of the technical equipment in the system, it shows up in the supply or return. Especially with heat pumps (also chillers), this can lead to the fact that depending on the temperature range of the heat pumps they are in the supply and return of the system at the same time.

**Comment by gtfierro** [comment]
TODOs:
- find some chilled|hot  water system examples and what terms they use. Maybe we can choose a consistent interpretation or context across them
