### ISSUE TITLE
The latest stable version (Brick.ttl 1.2.1) does not contain "rdfs:label" on Class

### ISSUE THREAD

**Issue by jonev** [BrickSchema/Brick#366]
The latest stable version (Brick.ttl 1.2.1) does not contain "rdfs:label" on Class.
Example;
From version 1.2.0:
```
brick:Point a owl:Class ;
    rdfs:label "Point" ;
    rdfs:subClassOf _:has_Point,
        brick:Class ;
    brick:hasAssociatedTag tag:Point .
```
From version 1.2.1:
```
brick:Point a owl:Class ;
    rdfs:subClassOf _:has_Point,
        brick:Class ;
    brick:hasAssociatedTag tag:Point .
```
I cant find this change in the [Release Notes for v1.2.1](https://brickschema.org/ontology/1.2).
Is this a bug, or a planned change?

**Comment by gtfierro** [comment]
Definitely not intentional, sorry! The pending v1.3.0 release has labels for all classes and a unit test to verify that this will continue to be so

**Comment by jonev** [comment]
That's great, thank you!
