### ISSUE TITLE
Swap out "externalRepresentation" stuff for separate ontology

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/Brick#367]
I've been working on generalizing the external representation stuff into its own ontology here: https://github.com/gtfierro/ref-schema . I am also posting this to the 223P development repository as well. Ideally we all (REC, Brick, 223P, etc) are using the same ontology for these external references

Do we want to remove the Brick-specific relationships/definitions and replace them with this external schema? Or perhaps fold the ref-schema work into this repository, or have them extend the Brick namespace?

**Comment by jbkoh** [comment]
I'm happy with using a common vocabulary set instead of maintaining our own.
