### ISSUE TITLE
versioning instance models

### ISSUE THREAD

**Issue by epaulson** [BrickSchema/Brick#370]
This is just a placeholder, but as part of #350 we should also add as a best practice always including some kind of version info in your Brick models. e.g. something like, for 'mybldg.ttl':

```ttl
# mybldg.ttl
@prefix bldg: <urn:example#> .
@prefix brick: <https://brickschema.org/schema/Brick#> .

<urn:example#> a owl:Ontology ;
    owl:imports <https://brickschema.org/schema/1.2/Brick#> .
```
We'd change the brick tooling to do this automatically for people who use the brick tooling, e.g. py-brickschema always adds that to new Brick graphs.

We had a longer discussion about this in the tools working group: 
https://github.com/BrickSchema/Brick/wiki/Tooling-Working-Group-Notes

**Comment by jbkoh** [comment]
What do we need to do in Brick ontology for this one?

**Comment by gtfierro** [comment]
Initial support for this feature here: https://github.com/BrickSchema/py-brickschema/pull/86/

I don't know if there's much in Brick itself that we need to do, save for documenting this pattern in the docs repo (which I will do soon)

**Comment by efjerb** [comment]
Hi
I'm starting up a model that includes some BRICK metadata. Is this still best practice, if I want to show which version the model was built with?

**Comment by efjerb** [comment]
Oh my, I keep overlooking content in the documentation.... Thanks for your answer!
