### ISSUE TITLE
uni_softcode issue

### ISSUE THREAD

**Issue by SahaPratik6267** [BrickSchema/Brick#382]
i am using python 3.9 and when i try to run a sample code its gives error that uni_softcode was not found in markupsafe. I tried downgrading markupsafe but still same

**Comment by gtfierro** [comment]
Hi @SahaPratik6267 can you tell us the command you are running and what the output is?

**Comment by SahaPratik6267** [comment]
[image: image.png]

simply installed brickschema by pip install brickschema and then trying to
run this example code.

not sure what is wrong. but one thing i noticed is if i change to python
3.10 then the error changes.

[image: image.png]

this is after i change to python 3.10 and run pip install brickschema

**Comment by gtfierro** [comment]
@SahaPratik6267 I believe we've fixed this issue in a beta release of `py-brickschema`. You can install with

```
pip install brickschema[all]==0.6.0a6
```

or if you want a 'lite' version w/ fewer features + dependencies

```
pip install brickschema==0.6.0a6
```
