### ISSUE TITLE
equipment spec information issues

### ISSUE THREAD

**Issue by JUNGWONN** [BrickSchema/Brick#395]
Hi, I want to input spec information in brick especially in case of equipment such as chiller, boiler etc..

For example, I'm about to add the capacity, voltage, efficiency of chiller. How can I do this? Using bricktag is available? and can I extent brick for this? 

thank you

**Comment by jbkoh** [comment]
Hi Jungwonn,

Brick does support modeling such properties. Please check Entity Properties
in our doc: https://docs.brickschema.org/metadata/entity-properties.html

You can find all the available Entity Properties in Brick here:
https://brickschema.org/ontology/1.2/#EntityProperties

Please let us know if you want to add new properties to the list. I'd be
happy to discuss possible options for that.

Thanks!


With regards,
Jason Koh

**Comment by JUNGWONN** [comment]
Thank you jason.  How can I available Entity Porperies, through (https://brickschema.org/ontology/1.2/#EntityProperties) this link? 
Can't find download button 

Thanks!

Best regards,
Jungwon

**Comment by gtfierro** [comment]
@JUNGWONN you can download the Brick ontology, which defines those properties, here: https://brickschema.org/resources/ . I would recommend the nightly build: https://github.com/BrickSchema/Brick/releases/download/nightly/Brick.ttl

Is this what you are looking for?

**Comment by JUNGWONN** [comment]
shizuku:cooling_tower a brick:Cooling_Tower ;
    brick:feeds shizuku:absorption_chiller ;
    brick:isFedBy shizuku:absorption_chiller ;
    brick:isPointOf shizuku:absorption_chiller_system ;
    brick:hasPoint shizuku:cooling_tower_outlet_temp_sensor,
        shizuku:cooling_tower_on_off_status ;
    brick:hasTag tag:Cooling,
        tag:Equipment,
        tag:Tower .


I've already constructed an ontology in this way.

I would like to add the specific information of the cooling tower.

For example, information such as capacitance 15 kW, voltage 440 V current 21 rpm 1760, etc.

thanks

**Comment by gtfierro** [comment]
My recommendation is to read through our [contributing how-to file](https://github.com/BrickSchema/Brick/blob/master/CONTRIBUTING.md) and submit a pull request adding those entity properties to the Brick schema so they can be available for everyone!

**Comment by JUNGWONN** [comment]
> My recommendation is to read through our [contributing how-to file](https://github.com/BrickSchema/Brick/blob/master/CONTRIBUTING.md) and submit a pull request adding those entity properties to the Brick schema so they can be available for everyone!

**Comment by JUNGWONN** [comment]
Thank you all!

best regard
Jungwon
