### ISSUE TITLE
QUDT units included in Brick.ttl inconsistent with QUDT specification

### ISSUE THREAD

**Issue by ektrah** [BrickSchema/Brick#426]
Brick.ttl currently includes a set of QUDT units that are defined like this:

```ttl
@prefix unit: <http://qudt.org/vocab/unit/> .

…

unit:BAR a unit:Unit ;
    rdfs:label "Bar"@en ;
    qudt:symbol "bar" .
```

However, in http://qudt.org/2.1/vocab/unit, units are defined like this:

```ttl
@prefix qudt: <http://qudt.org/schema/qudt/> .
@prefix unit: <http://qudt.org/vocab/unit/> .

…

unit:BAR
  a qudt:Unit ;
  …
  qudt:symbol "bar" ;
  …
  rdfs:label "Bar"@en ;
.
```

i.e. the units are instances of `qudt:Unit` instead of `unit:Unit`.

Is there are reason why the QUDT units need to be duplicated into Brick.ttl?

**Comment by gtfierro** [comment]
looks like the mistake is mine on line https://github.com/BrickSchema/Brick/blob/master/generate_brick.py#L854

We should also ensure we are distributing QUDT in a "packaged" Brick as part of the release process.
