### ISSUE TITLE
miscellaneous observations 1.3 draft

### ISSUE THREAD

**Issue by mcc513** [BrickSchema/Brick#434]
A couple random observations looking at the draft 1.3 release:

1. In 1.3 (and 1.2.1) there is a typo Fequency rather than Frequency with the tags
2. In 1.3 (and 1.2.1) points "Underfloor_Air_Plenum_Static_Pressure_Sensor" and "Underfloor_Air_Plenum_Static_Pressure_Setpoint" are not tagged with tag:Point 
3. in 1.3 Points "Damper_Position_Status", "Differential_Temperature_Setpoint", & "Refrigerant_Level_Sensor" have no associatedTags declared which make them different (incomplete?) when compared to all other point declarations.

Sorry I'm not tech savvy enough to assist fixing any of these.

**Comment by mcc513** [comment]
4. In 3.1 Points "Exhaust_Fan_Disable_Command" and "Exhaust_Fan_Enable_Command" and Equipment "Fresh_Air_Fan" are marked as depreciated but unlike the other ~50 points marked as depreciated the details of those points/equipment (tags and sh:rules) are still in the ontology.

**Comment by gtfierro** [comment]
Thanks for finding these! I've merged in the fixes in #435 -- I started this before I saw your work, @danhugo, but thanks for helping out as well :)
