### ISSUE TITLE
Sensor taxonomy inconsistency

### ISSUE THREAD

**Issue by hammar** [BrickSchema/Brick#437]
When looking at reasonable ranges for lastKnownValue/value, I noticed what I think are some inconsistencies in the sensor taxonomy. I'd love to submit fixes to the below, if you agree with my interpretations:

* Refrigerant_Level_Sensor
    * Is an owl:Class but not a sh:NodeShape
* Natural_Gas_flow_Sensor
     * Is a direct subclass of both Sensor and Flow_Sensor; the former assertion should be removed.
* Rain_Duration_Sensor (measuring the duration of rain during some time period)
    * Is currently a subclass of both Rain_Sensor (which per the documentation measures rain _amount_) and Duration_Sensor (which measures _duration_ of something). Suggest only the latter subclass assertion be kept. 
* PIR_Sensor
    * Is a subclass of both Motion_Sensor and Occupancy_Sensor
    * Per PIR_Sensor description, it measures _motion_. That is consistent with what the Internet says about PIR sensor capabilities.
    * Suggest removing subclass assertion to Occupancy_Sensor (a PIR sensor does not detect an unmoving occupant)
* Energy_Usage_Sensor 
    * Is a subclass of both Energy Sensor (implicitly, though that is my interpretation, a short-term sensor) and Usage Sensor (total consumption of something over some period of time)
    * Per the documentation, it seems the intent of this sensor is the latter
    * However, Usage_Sensor explicitly measures consumption of a _substance_ -- so if the above intent is true, perhaps this should be rephrased somewhat.
* Peak_Power_Demand_Sensor 
    * Is a subclass of both Power_Sensor (measuring "instantaneous power consumed" (implicitly: at any given point, e.g., right now)) and of Demand Sensor ("amount of power consumed by the use of some process")
    * Peak_Power_Demand_Sensor measures, per the docs, the highest demand _over a certain time span_
    * It seems this sensor is intended to fulfill the latter use case, so the former subclass assertion might be removed

**Comment by gtfierro** [comment]
Thanks for finding these! In #440 I've addressed `Natural_Gas_flow_Sensor`, `Rain_Duration_Sensor `, `Refrigerant_Level_Sensor`. We will discuss some of the other questions during a development meeting tomorrow and I'll get back to you with some suggestions.

**Comment by gtfierro** [comment]
Discussion on `Rain_Duration_Sensor`: change `Rain_Sesnor` to be a `Rain_Level_Sensor`; remove `Rain_Sensor` (deprecate to `Rain_Level_Sensor`. `Rain_Duration_Sensor` stays under `Duration_Sensor`
