### ISSUE TITLE
Light Command vs Lighting Command

### ISSUE THREAD

**Issue by jbkoh** [BrickSchema/Brick#439]
I missed `Light Command` has been added recently, but can't locate the original discussion thread, so I'm starting a new one.

`Light Command` sounds more like a command to a piece of Equipment, `Light` (e.g., `Fan Command`), while `Lighting Command` sounds more related to the lighting action (e.g., `Cooling Command`). I see that they are similar to each other and probably most people won't distinguish them, but for us, Brick, it is a consistency issue.

- If we want it to be a command to a device, we'd want to have the device type to be materialized, but we don't have `Light` as a type but only `Luminaire`. (regardless of the conclusion of this discussion, `Light` as a type may be more aligned to control concepts than `Luminaire`.)
- Lighting controllers often control multiple lights altogether, while `Light_Command` seems more for a single light.

Thus, I think `Lighting_Command` makes more sense and is generalizable.

1.3.0 release is about to be done, so I don't mind reflecting this in the next version, but figured it's worth discussing now.

**Comment by jbkoh** [comment]
@OskarNSE Maybe you are interested in this topic.

**Comment by OskarNSE** [comment]
Yes, thanks for pinging me! I'll look into it

**Comment by gtfierro** [comment]
I don't recall any conversation around `Light Command` but I'm ok with changing to `Lighting_Command`. Can you get a PR done this weekend?

**Comment by jbkoh** [comment]
Closing this and continue discussing at https://github.com/BrickSchema/Brick/pull/459
