### ISSUE TITLE
Add ColorTemperatureLightingCommand

### ISSUE THREAD

**Issue by nikosandronikos** [BrickSchema/Brick#445]
Proposal: Extending LightingCommand to allow colour temperature to be set as well.

ColorTemperatureLightingCommand extends LightingCommand.
Units would generally be in Kelvin. Mirek/mired seems to be missing from qudt, but would be desirable as well.

Not sure if this change would necessitate adding BrightnessLightingCommand? Is it ok for the super class to have a specific meaning if there are sub classes? What's the norm in Brick?

Happy to follow up with a PR if this is reasonable?

**Comment by cbupp** [comment]
Hey @nikosandronikos - I had a similar comment on the [open pull request](https://github.com/BrickSchema/Brick/pull/442)

**Comment by jbkoh** [comment]
Hi all,

Thanks for brining that up. I do have the need for color temperature as well and was about to file a PR for that. Lighting_Command presumed to change the light level not the temperature. It'd be nicer to be more explicit of course. I will create a separate PR including those two points.

**Comment by gtfierro** [comment]
@jbkoh just wanted to bump up this issue in your long queue of things to look at!

**Comment by jbkoh** [comment]
Thanks for the reminder. Will work on it tomorrow.

**Comment by jbkoh** [comment]
Closing this and continue discussing at https://github.com/BrickSchema/Brick/pull/459
