### ISSUE TITLE
Class hierarchy not shown on the website for Brick v1.1

### ISSUE THREAD

**Issue by filiphl** [BrickSchema/Brick#449]
Hi!

As of now, I am not able to see the class hierarchy of the ontology for [Brick v1.1](https://brickschema.org/ontology/1.1/#Classes). I do so for v1.2 and v1.3 though.

**Comment by gtfierro** [comment]
I think I may have fixed the issue in this PR: https://github.com/BrickSchema/brick-website/pull/159 

I'll see if the build is fixed and then I'll update the website today or tomorrow

(As an aside -- you should be using more recent versions of Brick! 1.3 is released now and is much improved over 1.1. Let me know if you have any issues with upgrading)

**Comment by gtfierro** [comment]
Should be fixed now!
