### ISSUE TITLE
Inconsistent use of abbreviations and capatialization

### ISSUE THREAD

**Issue by mbkj** [BrickSchema/Brick#45]
Suggestions by SDU Student Henrik Lange

The Brick definitions contain several abbreviations:
- AHU: Air Handler Unit
- CRAC Computer Room Air Condition
- CWS: Chilled Water System
- DHWC: Domestic Hot Water System
- FCP: Fire Control Panel
- FCU: Fan Coil Unit
- HVAC: Heat Ventilation Air Condition
- HWS: Hot Water System
- HX: Heat Exchanger
- PIR: Passive Infra Red (motion detector)
- PV: Photovoltaic
- VAV: Variable Air Volume
- VFD: Variable Frequency Drive
- WS: Water System
- DI: Deionized

While some of these abbreviations are commonly used in the building
industry, many are associated with a narrower field, such as electricity
or plumbing, or a smaller community, such as a single country. This
makes it difficult for someone to know them all across trades and cultures,
and finding translations online is not always easy. For instance, DI might
be confused with a Digital Input. In some instances, Brick supports the
same definitions with abbreviation and the full word; for instance, AHC
and Air Handler Unit are both listed as definitions. In some cases, the
abbreviation and the full phrase are both in the same definition, such as
CWS Chilled Water System Enable Command. The general syntax in
Brick is a combination of title case and snake case (Title Snake Case),
but in some definitions, it is combined with title case (TitleCase), such as
in HeatExchanger Outside Air Temperature High Reset Setpoint. This
means that the Brick syntax has 3 distinct ways of writing the same set of
keywords: In this case, HX, HeatExchanger and HeatExchanger are used
interchangeably between denitions. The words high, highest and max are
similarly also found, seemingly interchangeably throughout the definitions,
and the same goes for low, lowest and min.

A clear casing convention for definitions should be made. There is a clear tendency towards writing definitions in a combination of TitleCase and snakecase (TitleSnakeCase), but it is just a tendency, not a rule. A convention would make it easier for everyone to write the correct definition without having to check with the definition list every time. The selectied convention should be followed in the syntax and thus avoid combining casing structures, such as FireControlPanel Fire Control Panel Off Command. This problem becomes especially challenging in combination with the abbreviation problem, since a combination of these allows up to three different versions of the same words to exist. As an example, HeatExchanger, Heat Exchanger and HX all exist and are all used interchangeably in other definitions. This might mean that definitions become unclear and at worst, ambiguous, as an application looks for one definition where a programmer used another.
Use of the words max, high, highest, min, low and lowest is not ex- plained in the schema either. They might all mean the same, in which case.

**Comment by gtfierro** [comment]
Much agreed! Thanks for putting this together. 

There are a couple things we can do I think to help mitigate this (in order of increasing complexity/effort)
1. standardize on `Title_Snake_Case`
2. remove the names of equipment from point names: e.g. `Heat_Exchanger_Outside_Air_Temperature_High_Reset_Point` becomes `Outside_Air_Temperature_High_Reset_Point`, and can have an `isPointOf` relationship with a `Heat_Exchanger`. This will reduce the number of tagsets and the opportunities to use `HX`, `Heat_Exchanger` and `HeatExchanger` in what are essentially duplicate tagsets
3. possibly migrate to a refinement of https://github.com/BuildSysUniformMetadata/Brick/issues/36 in order to avoid human error in how the tagsets are constructed

Regarding high/max/highest/etc, there are a few of these that are redundant and a few of these that see more regular usage within certain subsystems. In general, though, I would agree that we should try to standardize the tag definitions and which tags are used.

Thoughts, @jbkoh? I know you've brought up the 2nd item before, and I think its a great idea, but I believe the current CSV approach is limiting how we can define/extend Brick.

**Comment by berkoben** [comment]
QQ: Why Title_Snake?  Do the caps add anything to the meaning?  If not, why not simplify?

Agree with 2.

**Comment by jbkoh** [comment]
Looks like I am late to the party. Thanks for pinning out an important issue, Mikkel.

### Answers to Mikkel's specific examples:

1. About the abbreviations: 
When we originally discussed the design of Brick, I was against of using abbreviations but there were requirements that the vocabularies should be familiar with the field engineers. Some abbreviation such as VAV are obviously more prevailing than their original words. However, it resulted in the overuse of abbreviations. I'd suggest removing most of the abbreviations except popular and unambiguous ones. In Mikkel's list, I'd only include VAV, AHU and HVAC (maybe FCU). The other abbreviations seem not much useful.

2. The CWS_Chilled_Water_System_Enable_Command is a bad case created by the Brick generation script. I'd say it is a bug. 

3. I presume that our original design was Titile_Snake_Case. HeatExchanger looks like a bug to me. We can change it temporarily as a hotfix.

4. I agree that high, highest, max look confusing. Those vocabularies need to be i) documented and ii) reviewed. We do not have either of them, which is a big problem that I can't solve alone. Untimately, we need a through review of those vocabularies from the field engineers (like people from ASHRAE or the company engineers). I bring up this issue to JCI and hopefully we could extend this discussion to the practice. In my *personal* understanding, the definitions of high/highest/max are:
    1. high: somewhat high, the degree of highness does not have to be specific. E.g., CO2_High_Alarm.
    2. highest: a sample among various ranges. It's used for Sensors. E..g, Highest_Zone_Temperature_Sensor -> the highest temperature of the zone in certain time range.
    3. max: allowed maximum value of the target. It's used for Setpoints: E.g., Max_Air_Flow_Setpoint. 
    4. Again, these are my arbitrary understanding of the vocabularies and we need a review from the field engineers.


### Now, more generally, what should be our standard composition rules?
1. I don't recall the reasoning of Title_Snake_Case. I am be happy to move to snake_case. Shall we have a poll for this?

2. To Gabe's three proposals:
    1. I think it should be a hotfix to standardize everything to Title_Snake_Case. I consider they are bugs if not following it.
    2. I still think removing Equipment in Points tagsets is useful. Of course, there are Point tagsets needing Equipment types such as Fan_Command. In this case, I think "Fan" is a target resource but not representing its belonging. I can try to mitigate the CSV problem after the BuildSys deadline.
    3. I agree creating the general rule for tagset construction is more desired. It would be mostly about rules for describing target "resources" of Points, which may follow English syntax anyway.

3. @berkoben I agree that we might lose some usability by removing equipment from the name. One can query based on the relationships (e..g, using ``?point bf:isPointOf :ahu1``), but it might be easier to subclass "AHU_Flow_Sensor", etc. However, I think it is not difficult to add a relational pattern for querying, which gives more clear definition of the query. 

    1. For the usability, what Gabe and I discussed was to i) simplify/reduce the tagsets, ii) rely on explicit relationships, and iii) add annotation tags automatically generated from the explicit relationships. One can use the third feature if relational queries became difficult to sort out.

**Comment by henriklange** [comment]
No matter which abbreviations are kept, the list must be available on brickschema.org, as the knowledge of abbreviations is specific to the programmer who might work in HVAC systems, electricity, be a college student or something completely different. 

As per the Title_Snake_Case or simply snake_case, an argument could be made that ignoring case removes a possible error and would not break compatibility. Then, casing just becomes semantics. However, Title_Snake_Case is obviously prevalent at the moment, so sticking with that also makes sense.

Another thing from the report that should have been mentioned is that the definition of tagsets only exists for 179 tagsets out of 2,060 in version 1.0.2 . Version 1.0.3 has 296 definitions in total. These definitions are crucial to the success of brick, as they are what developers look for to make sure they selected the right one. At least I did.

**Comment by gtfierro** [comment]
@henriklange Could you file a separate issue for expanding the definitions?

@jbkoh @berkoben I'm not sure I understand this:
> With an equipment specific name you can define inter-point relationships for that equipment: AHU_airflow_sensor1 AHU_damper_position. This is still possible in the case where names are typically more generic by applying subclassing, but it's more complicated. I think this is a tradeoff worth making, but it should be noted that it is a tradeoff.

Is the argument that we would lose the ability to apply restrictions to points that are associated with certain kinds of equipment?  I.e. if I want to restrict the relationships that dampers in AHUs can have, but not dampers in VAVs?

**Comment by berkoben** [comment]
Sorry, my carats were removed...
`AHU_airflow_sensor1 <some relationship>  AHU_damper_position`
and yes, you got my point.  Though again, this is really just pedantry.  In practice it's still possible to do this, it's just becomes a special case instead of the default.

**Comment by gtfierro** [comment]
In the upcoming v1.1.0 release, we have taken steps to address the issues raised here:

- The redundant parts of Classes (née TagSets) have been removed
- Relationships between points and equips are done via the `isPointOf` relationship
- no reliance upon the lexical form of the class names

We are side stepping structured tagset generation from tags by introducing the Python structure that contains all of the classes and their constituent tags in explicit definitions. We can explore simplifying this further in the future, but its sufficient and hackable enough for now.
