### ISSUE TITLE
Transitivity for hasPart

### ISSUE THREAD

**Issue by SBlechmann** [BrickSchema/Brick#451]
Hey there,

I was just wondering why there is no transitivity for the hasPart / isPartOf properties.

I saw in some older documentation that both hasPart and feeds were supposed to be transitive properties. Then I found your discussion for the v1.1 (https://github.com/BrickSchema/brick-owl-dl/issues/15) release and I understand some background and why feeds is not transitive.
Yet, I could not find information on why hasPart / isPartOf are not transitive. 

I appreciate you taking the time to clarify this :)

**Comment by gtfierro** [comment]
Hi @SBlechmann -- the basic reason for removing the transitivity is to allow consumers of Brick to properly differentiate between the "1 hop" and the "*n* hop" hasPart relations. SPARQL can always produce the transitive relationship at query time using property paths; it is also fairly straightforward to construct the transitive relationship using other means as well. 

If the transitivity is enforced by the reasoner, then there is no way to reconstruct what the non-transitive ("1 hop") relationships were. Hope that clears things up!

**Comment by gtfierro** [comment]
Sure! It's the `+`/`*` operators.

So if I had a Brick model like:

```ttl
:building a brick:Building ;
  brick:hasPart :floor1 .

:floor1 a brick:Floor ;
  brick:hasPart :room1, :room2 .

:room1 a brick:Room .
:room2 a brick:Room .
```

I could query from the building to find all of the rooms using a transitive closure on the `hasPart` relation:

```sparql
SELECT ?room WHERE {
  :building brick:hasPart+ ?room .
  ?room a brick:Room
}
```
