### ISSUE TITLE
CRAC and CRAH

### ISSUE THREAD

**Issue by JoelBender** [BrickSchema/Brick#46]
I was stumbling around the TTL files trying to find out what CRAC was, finally found it, and I would like to rename `Computer_Room_Air_Conditioning` to `Computer_Room_Air_Conditioner` as an equipment class rather than something that describes a process.  In the process I found [this article](http://www.dchuddle.com/2011/crac-v-crah/) and I'm curious if there should be a similar distinction in Brick with an additional family of CRAH classes.

**Comment by jbkoh** [comment]
@JoelBender I feel guilty as I haven't been responsive to the Issues for a while. I would like to clean up dangling Issues in the next two weeks. The different between CRAC vs CRAH is the cooling agency and relevant controllers. Our next version can handle this without introducing new terms by expressing what substances equipment uses, so I'd like to have CRAC only. However, if there is enough consensus (i.e., requests from other people). we can definitely discuss further.

I will close this now, but please reopen it if you think it deserves a more discussion.
