### ISSUE TITLE
Absolute vs relative humidity sensor

### ISSUE THREAD

**Issue by hammar** [BrickSchema/Brick#461]
At present there is

* Sensor
    * Humidity_Sensor
        * Relative_Humidity_Sensor

But no class for absolute humidity. I propose either of the following:

* Sensor
    * Humidity_Sensor
        * Absolute_Humidity_Sensor
        * Relative_Humidity_Sensor

_OR_

* Sensor
    * Absolute_Humidity_Sensor
    * Relative_Humidity_Sensor

Would a pull request for either of these be of interest?

Karl

**Comment by gtfierro** [comment]
Thank you! I think we'd prefer having absolute humidity sensor be a sibling of relative humidity sensors

**Comment by hammar** [comment]
PR submitted.
