### ISSUE TITLE
Eliminate undefined measurements

### ISSUE THREAD

**Issue by JoelBender** [BrickSchema/Brick#47]
I believe the `UndefinedMeasurement` class members are those things that use the `UndefinedMeasurment` tag, but other than that, the class doesn't seem to be useful.  For example, a battery voltage is an [observable property](https://www.w3.org/TR/vocab-ssn/#SOSAObservableProperty):
```
:Battery_Voltage a owl:Class ;
    rdfs:label "Battery Voltage"@en ;
    rdfs:subClassOf :UndefinedMeasurement .
```
It seems odd to subdivide something undefined :-).

**Comment by gtfierro** [comment]
No more `:UndefinedMeasurement` in the current release (v1.1.0). in the future, we may want to align our quantities classes with SSN's Observable Properties, but I'll leave that for future work
