### ISSUE TITLE
Restructure the temperature control setpoints

### ISSUE THREAD

**Issue by jbkoh** [BrickSchema/Brick#502]
We have many inconsistent names related to temperature setpoints while even they are not complete enough to model all we see in building systems. Here is the list of them: https://gist.github.com/jbkoh/8047ba76d267a6d14f9d91d68729d5bf

E.g., There are cooling temperature setpoints and temperature cooling setpoints at the same time. I'd like to propose restructure the names and the hierarchy.

All the related classes have those dimensions
1. When: Occupied/Unoccupied/Standby (or agnostic to when)
2. Substance: Air/Zone_Air/Supply_Air (for this discussion, I don't mind limiting to Zone_Air)
3. MeasurementProperty: Temperature
4. IntendedBehavior: Cooling/Heating/Target (I coined the term "target" for now to represent the single value desired by the controller. More to discuss below) 
5. (how the value was set: Effective/Remote/Local/Override)<- I will discuss this in a separate thread.

As an example, Unoccupied_Cooling_Temperature_Setpoint means the temperature setpoint when a terminal unit will kick cooling when the zone is unoccupied.

*Thus, I propose to align all the names to `{When}_{Substance}_{IntendedBehavior}_Temperature_Setpoint`*

And for "Target", in some systems, it's often called "common setpoint". It's a target setpoint from which deadband setpoints are set by a deadband width. We don't have a dedicated term for that, but rather used "Zone_Air_Temperature_Setpoint" for representing that, assuming that's the target temperature setpoint that a zone is desired to follow. However, due to the term's generic nature, our class hierarchy added "Zone_Air_Cooling_Temperature_Setpoint" to be a subclass of "Zone_Air_Temperature_Setpoint", so if I really want to set the setpoint of the zone's target temperature, I need to query for "a Zone_Air_Temperature_Setpoint which are not a Zone_Air_Cooling_Temperature_Sepoint or a Zone_Air_Heating_Temperature_Setpoint". That is 1) not ideal developer experience and 2) hard to educate that for all the users in the Brick community.

*Thus, I propose to introduce some term like "Target". (I'm not attached to that specific term, just putting "Target" as a placeholder. I'm open to any proposals)*

We are missing "standby" setpoints, which has the same level of effectiveness as "occupied" and "unoccupied". 

*I propose to add all the standby points for cooling/heating temperature setpoints (or we can branch out "Cooling Temperature Setpoint" from "Temperature Setpoint".)*.

Another thing to think about is the terms "cooling" and "heating" here. We could make them even more explicit as "upper bound of a deadband" and "lower bound of a deadband'.  Maybe "Upper_Deadband_Setpoint" and "Lower_Deadband_Setpoint". It's more neutral to the behavior and generic to other deadband controls. But it will require us to update "Deadband_Setpoint" into something like "Deadband_Width_Setpoint" or so, which I also like (being more explicit is better Maybe it's against common practices in the industry.

*I'm neutral to this idea and want to learn more about others' opinions.*

The other way of solving this issue is to use properties/tags instead of typings for modeling this. E.g., we can add intended behaviors and effective condition (when) as properties. I don't have a solid proposal to this yet, though I'm open to changing our direction to there too, if the current design generates too many classes without usage.

Once we have an agreement, I will create a PR.

**Comment by gtfierro** [comment]
I'm going to close this because we addressed it in #506
