### ISSUE TITLE
Inquiry: how to get union querying features for the VersionedGraphCollection?

### ISSUE THREAD

**Issue by rileywong311** [BrickSchema/Brick#513]
## Question

The cool thing about `GraphCollection` in BrickSchema is that it seems you can load your `Brick.ttl` metadata separately from another Brick graph. This means I can isolate my own Brick graph from the collection and serialize it without all the `Brick.ttl` metadata in it, but at the same time use its union with the `Brick.ttl` file to make more general queries on my graph. For example, I can only tell if `BRICK.Zone_Air_Temperature_Sensor` is a subclass of `BRICK:Temperature_Sensor` when querying the union of my own graph and the `Brick.ttl` graph. (I am basing this on the second example listed in the documentation [here](https://brickschema.readthedocs.io/en/latest/graph.html))

I would like the same feature with the `VersionedGraphCollection` but am having a hard time figuring it out. Is this possible?

## Attempts Listed Below

One attempt at this was to load a `VersionedGraphCollection` into a `GraphCollection`, but it doesn't seem to work (this is a modification of the second example in the documentation linked above):

``` py
from brickschema.graph import GraphCollection
from brickschema.persistent import VersionedGraphCollection
from brickschema.namespaces import BRICK, A
from rdflib import URIRef, Namespace

gc = GraphCollection()

gc.load_graph("https://sparql.gtf.fyi/ttl/Brick1.3rc1.ttl", format="turtle")

BLDG = Namespace("urn:building-instance/")

bldg_graph = gc.graph(VersionedGraphCollection("sqlite://"))

with bldg_graph.new_changeset("my-building") as cs:
  cs.add((BLDG["my-building"], A, BRICK.Building))
  cs.add((BLDG["my-sensor"], A, BRICK.Zone_Air_Temperature_Sensor))

res = gc.query("""SELECT * WHERE {
    ?sensor rdf:type/rdfs:subClassOf* brick:Temperature_Sensor
}""")

print(len(res)) # the len(res) is 0

assert len(res) == 1
```

Perhaps another solution could be to have a `VersionedGraphCollection` and a `GraphCollection` with the `Brick.ttl` file loaded into it exist seperately, then when I want to query the latest version of the `VersionedGraphCollection` somehow move a reference to that graph into the `GraphCollection` then remove it when I'm done querying.  Some code attempts for that look like this:

``` py
from brickschema.persistent import VersionedGraphCollection
from brickschema.namespaces import BRICK, A
from rdflib import URIRef, Namespace

vgc = VersionedGraphCollection("sqlite://")

BLDG = Namespace("test:") 

with vgc.new_changeset("my-building") as cs:
    cs.add((BLDG.vav1, A, BRICK.VAV))
    cs.add((BLDG.zone1, A, BRICK.HVAC_Zone))

### querying the versioned graph directly (and it works) ###

vgc.serialize("test1.ttl")

res = vgc.query("SELECT * WHERE { ?x a brick:VAV }")
print(len(list(res)))

### trying to get the latest version of the versioned graph (for some reason doesn't find the VAV)###

snapshot = vgc.latest_version['timestamp']
g = vgc.graph_at(timestamp=snapshot)
g.serialize("test2.ttl")

res = g.query("SELECT * WHERE { ?x a brick:VAV }")
print(len(list(res)))

### loading into a graph collection (also doesn't work) ###

gc = GraphCollection()
gc.load_graph("https://sparql.gtf.fyi/ttl/Brick1.3rc1.ttl", format="turtle")

gc.graph(g)

res = gc.query("SELECT * WHERE { ?x a brick:VAV }")

print(len(res))
```

Let me know if these explanations don't make sense. Otherwise, any insight on this is appreciated!

**Comment by gtfierro** [comment]
@rileywong311 can you try `brickschema==0.7.1a5` and see if it works?

**Comment by rileywong311** [comment]
I'll try it out later tonight!

**Comment by rileywong311** [comment]
To first address your `.load_graph()` vs `.grap()` -- From what I've seen, I think it is actually `.graph()` which adds a graph to a GraphCollection, it does this on top of retrieving it. `.load_graph()` seems to be only for file paths.

Moving on to the testing -- I think it still doesn't work. Here is a slightly modified version of the first attempt:

``` py
from brickschema.graph import GraphCollection
from brickschema.persistent import VersionedGraphCollection
from brickschema.namespaces import BRICK, A
from rdflib import URIRef, Namespace

gc = GraphCollection()

gc.load_graph("https://sparql.gtf.fyi/ttl/Brick1.3rc1.ttl", format="turtle")

BLDG = Namespace("urn:building-instance/")

print(gc.graph_names)

bldg_graph = gc.graph(VersionedGraphCollection("sqlite://"))

print(gc.graph_names) # there is a new graph in here, so it did add?

with bldg_graph.new_changeset("my-building") as cs:
  cs.add((BLDG["my-building"], A, BRICK.Building))
  cs.add((BLDG["my-sensor"], A, BRICK.Zone_Air_Temperature_Sensor))

### QUERYING TESTS BELOW ###

### From graph collection with subClassOf query ###

res = gc.query("""SELECT * WHERE {
    ?sensor rdf:type/rdfs:subClassOf* brick:Temperature_Sensor
}""")

print(f"From graph collection with subClassOf: {len(res)}")


### Directly from graph with subClassOf query (shouldn't work) ###

res2 = bldg_graph.query("""SELECT * WHERE {
    ?sensor rdf:type/rdfs:subClassOf* brick:Temperature_Sensor
}""")

print(f"Directly from graph with subClassOf (shouldn't work): {len(res2)}")


### From graph collection but as actual type ###

res3 = gc.query("""SELECT * WHERE {
    ?sensor rdf:type/rdfs:subClassOf* brick:Zone_Air_Temperature_Sensor
}""")

print(f"From graph collection but as actual type: {len(res3)}")


### Directly from graph but as actual type ###

res4 = bldg_graph.query("""SELECT * WHERE {
    ?sensor rdf:type/rdfs:subClassOf* brick:Zone_Air_Temperature_Sensor
}""")

print(f"Directly from graph but as actual type: {len(res4)}")

for b in res4.bindings:
  print(b)
```

Only the last query which is directly on the versioned graph and the exact type the entity is works. 


Putting a `VersionedGraphCollection` into a `GraphCollection` also has been returning this error, although it doesn't inhibit the code from running:
```
2023-05-22:20:59:10,215 WARNING [__init__.py:630] caught a TypeError, retrying call to <class 'rdflib_sqlalchemy.store.SQLAlchemy'>.bind without override, see https://github.com/RDFLib/rdflib/issues/1880 for more info
Traceback (most recent call last):
  File "C:\Users\yelir\Documents\BrickSchemaTests\venv\lib\site-packages\rdflib\namespace\__init__.py", line 627, in _store_bind
    return self.store.bind(prefix, namespace, override=override)
TypeError: SQLAlchemy.bind() got an unexpected keyword argument 'override'
```

**Comment by gtfierro** [comment]
> To first address your `.load_graph()` vs `.grap()` -- From what I've seen, I think it is actually `.graph()` which adds a graph to a GraphCollection, it does this on top of retrieving it. `.load_graph()` seems to be only for file paths.

Can you show where you're getting this impression? We might have unclear documentation. You can see from the `load_graph` [documentation](https://brickschema.readthedocs.io/en/latest/source/brickschema.html#brickschema.graph.GraphCollection.load_graph) that it accepts several arguments, including an `rdflib.Graph` object directly. The `.graph()` method only takes a graph name as an argument -- this is inherited from [`rdflib.Dataset`](https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.html#rdflib.graph.Dataset.graph)

**Comment by gtfierro** [comment]
> Putting a `VersionedGraphCollection` into a `GraphCollection` also has been returning this error, although it doesn't inhibit the code from running:
> 
> ```
> 2023-05-22:20:59:10,215 WARNING [__init__.py:630] caught a TypeError, retrying call to <class 'rdflib_sqlalchemy.store.SQLAlchemy'>.bind without override, see https://github.com/RDFLib/rdflib/issues/1880 for more info
> Traceback (most recent call last):
>   File "C:\Users\yelir\Documents\BrickSchemaTests\venv\lib\site-packages\rdflib\namespace\__init__.py", line 627, in _store_bind
>     return self.store.bind(prefix, namespace, override=override)
> TypeError: SQLAlchemy.bind() got an unexpected keyword argument 'override'
> ```

Yes, this is a known issue in the `rdflib_sqlalchemy` package

**Comment by gtfierro** [comment]
Can you restructure your test code to emit warnings or assertions so that it is clear what the expected behavior is? This will help me debug. Thanks!

**Comment by rileywong311** [comment]
- Can you restructure your test code to emit warnings or assertions so that it is clear what the expected behavior is? This will help me debug. Thanks!

I'm not sure if I can emit warnings since it comes with adding a VersionedGraphCollection into a GraphCollection, which might not even work (but it would provide the feature I'm looking for). 

- Can you show where you're getting this impression? We might have unclear documentation. You can see from the load_graph [documentation](https://brickschema.readthedocs.io/en/latest/source/brickschema.html#brickschema.graph.GraphCollection.load_graph) that it accepts several arguments, including an rdflib.Graph object directly. The .graph() method only takes a graph name as an argument -- this is inherited from [rdflib.Dataset](https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.html#rdflib.graph.Dataset.graph)


This is a copy of the second example from this [documentation ](https://brickschema.readthedocs.io/en/latest/graph.html). I've only added `print(g.graph_names)` before and after the `bldg_graph = g.graph(URIRef(BLDG))`
``` py
from brickschema.graph import GraphCollection
from brickschema.namespaces import BRICK, A
from rdflib import URIRef, Namespace

# in-memory graph
g = GraphCollection()

# load Brick ontology
g.load_graph("https://sparql.gtf.fyi/ttl/Brick1.3rc1.ttl", format="turtle")

# declare namespace for the entities in the "instance" model
BLDG = Namespace("urn:building-instance/")

# grab the graph for the building instance model so we can add triples to it

print(g.graph_names)

bldg_graph = g.graph(URIRef(BLDG))

print(g.graph_names)

# now we can add triples to the building
bldg_graph.add((BLDG["my-building"], A, BRICK.Building))
bldg_graph.add((BLDG["my-sensor"], A, BRICK.Zone_Air_Temperature_Sensor))

# when we run queries, run them against the "collection"
res = g.query("""SELECT * WHERE {
    ?sensor rdf:type/rdfs:subClassOf* brick:Temperature_Sensor
}""")
assert len(res) == 1

# we can save the building graph separately
bldg_graph = g.graph(URIRef(BLDG))
bldg_graph.serialize("my-building.ttl", format="turtle")
```

**Comment by gtfierro** [comment]
In the example code above, the `g.graph` method is *retrieving* a graph object, which can then be edited. It does not take a graph as an argument. You need to use the correct keyword argument with `load_graph` to get the desired behavior: `g.load_graph(graph=my_graph_object)`

> adding a VersionedGraphCollection into a GraphCollection

Are you trying to nest these? I'm not clear on the use case for putting a VersionedGraphCollection inside a GraphCollectiion -- wouldn't this just be solved by using a VersionedGraphCollection directly?

**Comment by rileywong311** [comment]
> You need to use the correct keyword argument with load_graph

I didn't use the keyword `graph=`, so I'll look into that. Thank you!

> Are you trying to nest these? I'm not clear on the use case for putting a VersionedGraphCollection inside a GraphCollectiion -- wouldn't this just be solved by using a VersionedGraphCollection directly?

The reason I am trying to combine `VersionedGraphCollection` and `GraphCollection` is so that I can separate the generic `Brick.ttl` file from the graph I will be doing versioned history on. That way I can eventually retrieve just the `VersionedGraphCollection` and `serialize` it without all the `Brick.ttl` metadata in it also. This is demonstrated in the [second example](https://brickschema.readthedocs.io/en/latest/graph.html) I've been trying to modify. There may be another approach to this, but this seems the most plausible solution that I can think of.

**Comment by rileywong311** [comment]
I think that `graph=` worked! Here's a tiny example:

``` py
from brickschema.graph import GraphCollection
from brickschema.persistent import VersionedGraphCollection
from brickschema.namespaces import BRICK, A
from rdflib import URIRef, Namespace

gc = GraphCollection()

gc.load_graph("https://sparql.gtf.fyi/ttl/Brick1.3rc1.ttl", format="turtle")

BLDG = Namespace("urn:building-instance/")

print(gc.graph_names)

vgc = VersionedGraphCollection("sqlite://")

with vgc.new_changeset("my-building") as cs:
  cs.add((BLDG["my-building"], A, BRICK.Building))
  cs.add((BLDG["my-sensor"], A, BRICK.Zone_Air_Temperature_Sensor))
gc.load_graph(graph=vgc)

### From graph collection with subClassOf query ###

res = gc.query("""SELECT * WHERE {
    ?sensor rdf:type/rdfs:subClassOf* brick:Temperature_Sensor
}""")

print(f"From graph collection with subClassOf: {len(res)}") # finds it because len(res) = 1
```

How would I access this VersionedGraphCollection here to add more entities to it and eventually redo/undo?

**Comment by gtfierro** [comment]
The entire collection is versioned; not just a single graph. You would use a VersionedGraphCollection (VGC for short) to manage all of that; nesting GraphCollections inside a VGC is not supported because the underlying representations are incompatible. I would load in the Brick ontology into your VGC and then add in your building graph to the collection (under a different graph name). This will provide the functionality you are looking for . If you just want the building graph, extract it from the VGC using the `.graph(my_building_uri)` method (assuming `my_building_uri` contains the name of the building graph in the VGC)

**Comment by rileywong311** [comment]
Ok thanks! I'll try this out. Sorry for the confusion of the other attempts then!

**Comment by Moult** [comment]
@gtfierro for context this is part of GSoC :) to implement undo/redo and saving the project's TTL independently from the Brick.ttl

**Comment by rileywong311** [comment]
Yes indeed 😎! 

Also, I've gotten the VersionedGraph to store `Brick.ttl` and other graphs separately. Here's the working code:

```py
from brickschema.persistent import VersionedGraphCollection
from brickschema.namespaces import BRICK, A
from rdflib import URIRef, Namespace

vgc = VersionedGraphCollection(uri="sqlite://")

with vgc.new_changeset("Brick") as cs:
    cs.load_file("https://sparql.gtf.fyi/ttl/Brick1.3rc1.ttl")

BLDG = Namespace("test:") 

with vgc.new_changeset("my-building") as cs:
  cs.add((BLDG["my-building"], A, BRICK.Building))
  cs.add((BLDG["my-sensor"], A, BRICK.Zone_Air_Temperature_Sensor))

g = vgc.graph_at(graph="my-building")

res = vgc.query("""SELECT * WHERE {
    ?sensor rdf:type/rdfs:subClassOf* brick:Temperature_Sensor
}""")

assert len(res) == 1

g.serialize("VersionGraphMetadata.ttl")

vgc.undo()

g = vgc.graph_at(graph="my-building")

g.serialize("VersionGraphMetadata2.ttl")
```

With that, unless you see anything else, I believe this issue can be closed.

**Comment by gtfierro** [comment]
Thanks for the heads up, @Moult :)

Glad you got it working, @rileywong311! What you will find fairly soon is that the implementation is quite slow -- there is lots of unnecessary serialization and moving around of bytestrings that could just be simple IDs. If you are willing/interested to learn some Rust, I have some work that tries to make this same functionality much more performant and space efficient. Up to @Moult as to what he feels the focus should be, but I figured I would ask!

**Comment by gtfierro** [comment]
@rileywong311 would you be able to add the example you produced as some documentation to the https://github.com/BrickSchema/py-brickschema repository? I think this would be very helpful for future users!

**Comment by rileywong311** [comment]
Hi, just saw this now after we closed the issue. I created a pull request for some possible new documentation.

The Rust implementation could be promising! There is other focus in the project right now, but I think I would like to look at this at some point!
