### ISSUE TITLE
Temperature sensors - equipment or points?

### ISSUE THREAD

**Issue by efjerb** [BrickSchema/Brick#521]
Hi,

I hope that it's okay that I write a question here. If not, don't hesitate to close/delete the issue.
I'm struggling a bit with understanding the distinction between points and equipment. Of course, it is clear to me that fans are equipment that could have multiple points. But what about a pressure sensor in a duct system in a duct system? I would argue that it could be a single piece of equipment. I realize that in many cases, it would probably part of the AHU, but in some cases you want to control the pressure in multiple locations.

Best regards,
Esben

**Comment by gtfierro** [comment]
Hi @efjerb -- sorry for the delay!

A Point is an abstraction of a BMS point -- essentially the I/O "variable" that you read/write from. We do have a Sensor Equipment class if you want to model where the physical sensor is.

For modeling where measurements are conducted in a duct system, you would probably want to reach for an ontology like ASHRAE 223P. Adding this detail requires a fair amount of complexity for modeling these systems properly. We are working on pulling some of 223P's connection models so they are compatible with Brick, and you will be able to use Brick + 223P together, but it is unlikely that Brick will support modeling the ducts themselves. Does this help?

**Comment by efjerb** [comment]
Sorry for ghosting my own issue for 6 months!

I work with other "equipment-oriented" ontologies, such as the Flow Systems Ontology (FSO) (I suppose ifcOWL could also work), so that part is covered. In the case of a static pressure sensor, I would probably model the sensor with either FSO or the Brick Sensor class. But would the sensor point then be a point of both the sensor AND the AHU? Or is there a separate relationship to imply that a specific equipment is measuring a point? I hope my question makes sense!

**Comment by gtfierro** [comment]
No problem! 

> But would the sensor point then be a point of both the sensor AND the AHU?

Yes, at this point. We aren't currently differentiating those two scenarios. If you do have a physical sensor you want to capture, you can use `Sensor_Equipment` like I have in this example: https://docs.brickschema.org/modeling/terminal-units.html . You could have the room sensor also be a point of the VAV if you wanted to associate the data source with both the physical box as well as the unit using the data.

For an example of what this might look like in 223, see this example: https://docs.open223.info/guides/brick-rec.html#using-brick-points-with-223 . The property/Brick point and physical sensor are all separate entities. Does this help?

**Comment by gtfierro** [comment]
We're using a different documentation page, at least temporarily: https://ontology.brickschema.org . You can look at the Sensor Equipment class here: https://ontology.brickschema.org/brick/Sensor_Equipment.html

**Comment by efjerb** [comment]
Again, thank you! I will close the issue now.
