### ISSUE TITLE
Exploring human-computer interaction for ontologies using Brick

### ISSUE THREAD

**Issue by mhodki** [BrickSchema/Brick#548]
Hi Brick team, just wanted to reach out to you to let you know that last year we did an honours project on 'Exploring Human-Computer Interaction in Ontologies:A Case Study' and we used BRICK with our Facilities Management Team. I've just got around to uploading a youtube video of the honours student's talk if you are interested at https://youtu.be/KC8lRNHTYEM
She got 1st class honours for the thesis and I am happy to share it with you if that would be of interest. Let me have an email and I can send it. Melinda

**Comment by JoelBender** [comment]
I would like a copy, joel@carrickbender.com, thank you!

**Comment by gtfierro** [comment]
That's fantastic! Please send that my way as well, if you can. You can find my email at https://gtf.fyi

**Comment by mhodki** [comment]
Sorry only just seen your emails. I have asked Briana to email you!

**Comment by mhodki** [comment]
Copy of Briana's email of 14/3/2024
Hi Gabe & Joel, 

Hope this email finds you well! As outlined in this [github issue](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBrickSchema%2FBrick%2Fissues%2F548&data=05%7C02%7Cmelinda.hodkiewicz%40uwa.edu.au%7Ce04cc6ae62944fcbf17408dc43d4d1a5%7C05894af0cb2846d8871674cdb46e2226%7C0%7C0%7C638459828521570264%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=WdYq8%2BejWZ94%2BTWeh0pKrhQVYQPYQCaGeT73gEzcjw0%3D&reserved=0), I completed an honours project in 2022 on Exploring Human-Computer Interaction in Ontologies where I used Brick as part of my case study. I have attached my thesis and a short [presentation](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DKC8lRNHTYEM.&data=05%7C02%7Cmelinda.hodkiewicz%40uwa.edu.au%7Ce04cc6ae62944fcbf17408dc43d4d1a5%7C05894af0cb2846d8871674cdb46e2226%7C0%7C0%7C638459828521579592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=rhuxnduhgmMrs7JRgUTvMsnmVc%2F1p2uuTUutj8fJgG0%3D&reserved=0) I gave, if you are interested.

**Comment by jbkoh** [comment]
Just watched a video and thanks for the valuable research!

**Comment by gtfierro** [comment]
Thanks so much for sharing @mhodki !
