### ISSUE TITLE
Running "make test" fails with "no such file or directory"

### ISSUE THREAD

**Issue by jbulow** [BrickSchema/Brick#554]
Running `make test` ends with the following error:

```
cd tests/integration && bash run_integration_tests.sh
++ ls '*_test.sh'
ls: cannot access '*_test.sh': No such file or directory
```

**Comment by gtfierro** [comment]
This will be fixed in this PR: https://github.com/BrickSchema/Brick/pull/559

Out of curiosity, what shell environment are you using?

**Comment by jbulow** [comment]
I'm using zsh.

**Comment by gtfierro** [comment]
Thanks! I think this is fixed now. I'll close this but let me know if you run into any further issues
