### ISSUE TITLE
Window Contact Point

### ISSUE THREAD

**Issue by sn3kyJ3di** [BrickSchema/Brick#567]
I am trying to locate a point to represent the position of a window (opened or closed).  I see Window in barrier assests but I'm not seeing it as a point.  Am I missing it or is it missing?  The context is related to HVAC, typically if someone opens a window the HVAC equipment will want to know and act accordingly.

**Comment by gtfierro** [comment]
You would use an `Open_Close_Status` point associated with a Window entity

```ttl
:oc a brick:Open_Close_Status ;
  brick:isPointOf :window .
:window a brick:Window
```

**Comment by sn3kyJ3di** [comment]
If the point is monitoring multiple windows (# of magnetic switches wired in series), would this still be applicable?
