### ISSUE TITLE
Occupied_Heating_Discharge_Air_Flow_Setpoint

### ISSUE THREAD

**Issue by sn3kyJ3di** [BrickSchema/Brick#568]
In point-setpoints-airflow I see "Occupied_Heating_Discharge_Air_Flow_Setpoint" but I am looking for "Heating_Discharge_Air_Flow_Minimum_Setpoint".  The context is around a electric heating coil which require a minimum amount of airflow to prevent a high temperature safety.  This number is usually calculated by the kW rating and delta-T I believe.  Did I miss it somewhere?

**Comment by gtfierro** [comment]
You are looking for a Parameter class, not a Setpoint class in that case -- Parameters, specifically Limits, can place policies around other values like Setpoints. In this case the class you are probably looking for is `brick:Max_Occupied_Heating_Discharge_Air_Flow_Setpoint_Limit`
