### ISSUE TITLE
Update the sample data with the coming new version (1.1.0)

### ISSUE THREAD

**Issue by jbkoh** [BrickSchema/Brick#57]

**Comment by gtfierro** [comment]
Update the existing publicly released buildings to v1.1.0 from  the defunct v1.0.2

**Comment by shreyasnagare** [comment]
@gtfierro Where are we going to keep the example building models? I'm using `./examples/models`.

**Comment by gtfierro** [comment]
That should work for now. We will just need to update the README text to include that the building models are inside the `examples` directory

**Comment by shreyasnagare** [comment]
@gtfierro There are a lot of classes, relationships and tags (present in the v1.0.2 example building models) that have been deprecated or are missing in `v1.1.0`. Is there a Google Doc/Sheet where we can discuss this?


Example:

| Relationship | Deprecated? | Updated to  |
|--------------|-------------|-------------|
| isLocatedIn  | no          | hasLocation |
| ***          | yes         |             |

**Comment by gtfierro** [comment]
It would be a great idea to create one!

A large number of the deprecated classes will fall into this pattern:

```
:abc    a    brick:AHU_Temperature_Sensor
:abc    bf:isPointOf    :ahu1
```

gets replaced with

```
:abc    a    brick:Temperature_Sensor
:abc    brick:isPointOf    :ahu1
```

We remove the equipment names from the Point prefixes, and replace the old "brickframe" namespace with "brick" for consistency.

**Comment by gtfierro** [comment]
@jbkoh @shreyasnagare would you say this issue is taken care of now that #88 is merged?

**Comment by shreyasnagare** [comment]
I think it is. I'll also update the sample models on the website later today.

**Comment by gtfierro** [comment]
@shreyasnagare I didn't see any PR on the website to update the sample models. Could you take care of that today?

**Comment by shreyasnagare** [comment]
Done.

**Comment by gtfierro** [comment]
Great!
