### ISSUE TITLE
Where is the Brick Viewer?

### ISSUE THREAD

**Issue by bradjc** [BrickSchema/Brick#571]
http://viewer.brickschema.org/ doesn't load, can I run it myself?

**Comment by gtfierro** [comment]
You can, yes, but the code is pretty old (https://github.com/gtfierro/ttlviewer). I accidentally took it down when cleaning up some old infrastructure , and I'm planning on pushing the new version of it early next week.

**Comment by gtfierro** [comment]
There is an "alpha" version live right now at https://viewer.brickschema.org ! The basic stuff should work. You can also generate the "D2" string and paste it in over [here](https://play.d2lang.com/) to get a slightly nicer looking image.
