### ISSUE TITLE
brick:regulates in v1.3

### ISSUE THREAD

**Issue by emesar** [BrickSchema/Brick#575]
It appears that the `regulates` relationship is no longer part of the BrickSchema standard in v1.3. Was this intentional? I couldn't find mention of it in release notes.

**Comment by gtfierro** [comment]
Hi @emesar I don't believe it was ever an official part of Brick -- I believe the `regulates` relationship was added as an experiment but it was only ever added to a few classes. We removed the few uses of it to avoid future confusion and to make room for an eventual design to replace it. In particular, the emerging ASHRAE 223P standard should give us some concepts that will make modeling this a little easier. It would be great to discuss this with you; feel free to attend any of the upcoming Brick working group meetings (https://brickschema.org/blog/working-groups/)
