### ISSUE TITLE
Condenser Water Loop - Collection?

### ISSUE THREAD

**Issue by sn3kyJ3di** [BrickSchema/Brick#576]
I am not seeing a loop specific to a condenser water loop.  In particular I am thinking of an open cell cooling tower providing condenser water to fan coil/heat pumps for the cooling season, then it switches over to warmer water via boilers for the heating season.  Today I could use the more generic loop "Water_Loop", but this is a common HVAC system, does it warrant its own loop?

**Comment by gtfierro** [comment]
I think this makes sense to add! Do you want to open a PR to add this? This should only be a couple lines of code

**Comment by MatthewSteen** [comment]
I agree that Brick is missing this concept, which would complete the three loop types (CHW, HHW, and CW). This would allow more accurate modeling of water-cooled CHW systems and WSHP systems where a HW loop with boilers feeds the CW loop to maintain the high temp and the cooling towers maintain the low temp on the CW loop.
