### ISSUE TITLE
brick:aggregationFunction is an Owl:ObjectProperty but that doesn't match with Entity Properties Example

### ISSUE THREAD

**Issue by shayanfallahi** [BrickSchema/Brick#587]
It seems like in your ontology the brick:aggregationFunction is an Owl:ObjectProperty, while in your examples of modelling ([here](https://docs.brickschema.org/modeling/meters.html#)), the object of brick:aggregationFunction is a string. My humble opinion is: that makes the brick:aggregationFunction an owl:DatatypeProperty.

**Comment by gtfierro** [comment]
I think I agree! We'd welcome a PR to fix this in the distribution
