### ISSUE TITLE
Right way to model Setpoints

### ISSUE THREAD

**Issue by MaxBerktoldRWTH** [BrickSchema/Brick#615]
Hello together,

i was wondering how to model Temperature_Setpoints and stumbled across the example at `Brick/examples/rec-with-brick/building.ttl`.

In the Example a RVAV1 is a Variable_Air_Volume_Box_With_Reheat. Then we assign a AirTempSensor to it. So far i got it.
```
ex:RVAV1 a brick:Variable_Air_Volume_Box_With_Reheat ;

ex:AirTempSensor_RVAV1 a brick:Air_Temperature_Sensor ;
    brick:isPointOf ex:RVAV1 .
```
But then when creating an instance of Temperature_Setpoint it says that the AirTempSetpoint_RVAV1 hasPoint RVAV1. This makes no sense to me. Shouldn't it be brick:isPointOf?

```
ex:AirTempSetpoint_RVAV1 a brick:Temperature_Setpoint ;
    brick:hasPoint ex:RVAV1 .
```

I really appreciate the work that's been done here! Thanks.

**Comment by gtfierro** [comment]
You are correct! I'll make sure that's fixed soon
