### ISSUE TITLE
Mapping to other ontologies

### ISSUE THREAD

**Issue by cameronmore** [BrickSchema/Brick#617]
Is there a desire or plan to map to other ontologies like Basic Formal Ontology (BFO) or the Industrial Ontologies Foundry (IOF)? Mapping to something like the IOF or Common Core Ontologies (CCO) would provide more interoperability with other ontologies and would promote the use of this one by those communities.

**Comment by cameronmore** [comment]
That makes sense! If I see any opportunities, I will stay in contact with the repo/group!

**Comment by gtfierro** [comment]
Appreciate it! Let me know if you have any questions
