### ISSUE TITLE
Adjacent rooms

### ISSUE THREAD

**Issue by maxberktold** [BrickSchema/Brick#626]
Hello everyone,

I was wondering if it is possible to model adjacent rooms with Brick? Something like `ex:room1 brick:neighbouring ex:room2`

Since I haven't found a solution, I wanted to ask if this is planned to be added?

Greetings from Germany

Max

**Comment by gtfierro** [comment]
Hi @maxberktold -- did you find what you were looking for? I would recommend looking at the relationships in REC (https://doc.realestatecore.io); in Brick 1.4 we will be supporting these properties for locations, and I believe they do have an adjacency relationship (https://dev.realestatecore.io/ontology/Space/Architecture/Architecture)

**Comment by maxberktold** [comment]
Hi Gabe! A colleauge of mine just told me about the [BOT Ontology](https://w3c-lbd-cg.github.io/bot/). The BOT Ontology has a property called [adjacentZone](https://w3c-lbd-cg.github.io/bot/#adjacentZone) what was exactly what i was looking for.

Thank you for the hint! Propably i will be using the [adjacentElement](https://dev.realestatecore.io/ontology/Space/Architecture/Architecture) of the REC then. Looking forward to the release of 1.4!

Huge fan, thank you again!
