### ISSUE TITLE
In v1.4 lots of Points as direct subclasses of Thing

### ISSUE THREAD

**Issue by HervePruvost** [BrickSchema/Brick#632]
Hi,
Since v1.4, many "...Sensor" / "...Setpoint" / "...Parameter" classes have no subclass declaration which leads them to get out of the initial class hierarchy (brick:Class -> brick:Point -> etc...).

As a consequence, they are treated by ontology tools as direct subclasses of owl:Thing. 
For consistency with the rest of the points class structure, they should be declared as subclass of brick:Point or any relevant underlying subclass of it.

Please fix it in a next revision.
BR

**Comment by gtfierro** [comment]
Thanks for the heads up @HervePruvost ! Can you share an example of one of the classes you are talking about? We should be able to fix this in an upcoming point release or nightly build

**Comment by gtfierro** [comment]
Note to self: these show up on some of the aliases and possibly some of the deprecated classes, where the equivalent class and/or alias has the subclass relationship but the term in question does not

**Comment by HervePruvost** [comment]
Hi @gtfierro , among the classes I meant are for example **brick:Discharge_Air_Humidity_Sensor**, **brick:Occupied_Cooling_Discharge_Air_Flow_Setpoint** or **brick:Discharge_Air_Flow_Demand_Setpoint**... There are a lot of them. 

They have indeed some **equivalentClass** properties and do not have any **subClassOf** properties, contrary to the other points which are correctly nested into the Brick:Point tree and have **subClassOf** properties.

**Comment by gtfierro** [comment]
Thanks for the quick response! We should be able to fix this by next week
