### ISSUE TITLE
Brick v1.4.1 classes are missing labels

### ISSUE THREAD

**Issue by sarahmacSE978** [BrickSchema/Brick#659]
Is it a mistake that some Brick classes are missing labels in Brick v1.4.1 vs. Brick 1.4.0?

For Example:
brick:Cooling_Valve had a label in 1.4.0, but not in 1.4.1.

Could these labels be included in Brick v1.4.1?

**Comment by gtfierro** [comment]
The nightly build will have the RDFS labels, and I will include them in a v1.4.2 release (possibly next week?)
