### ISSUE TITLE
Empty property list for qudt:SystemOfQuantityKinds

### ISSUE THREAD

**Issue by desolat** [BrickSchema/Brick#664]
Checked for 1.4.1 and nightly.

Following up on #656 I tried some more with the Stardog import and with `Brick+imports.ttl` I got one "real" error:

![grafik](https://github.com/user-attachments/assets/5a1ddadc-1086-4929-8089-f41fb950cfe8)

The causing construct seems to be 

```
qudt:SystemOfQuantityKinds a rdfs:Class,
        sh:NodeShape ;
    rdfs:label "System of Quantity Kinds"^^xsd:string ;
    rdfs:comment "A system of quantity kinds is a set of one or more quantity kinds together with a set of zero or more algebraic equations that define relationships between quantity kinds in the set. In the physical sciences, the equations relating quantity kinds are typically physical laws and definitional relations, and constants of proportionality. Examples include Newton’s First Law of Motion, Coulomb’s Law, and the definition of velocity as the instantaneous change in position.  In almost all cases, the system identifies a subset of base quantity kinds. The base set is chosen so that all other quantity kinds of interest can be derived from the base quantity kinds and the algebraic equations. If the unit system is explicitly associated with a quantity kind system, then the unit system must define at least one unit for each quantity kind.  From a scientific point of view, the division of quantities into base quantities and derived quantities is a matter of convention."^^rdf:HTML ;
    rdfs:isDefinedBy <http://qudt.org/2.1/schema/shacl/qudt> ;
    rdfs:subClassOf qudt:Concept,
        qudt:Verifiable ;
    sh:property [ ],
        qudt:SystemOfQuantityKinds-baseDimensionEnumeration,
        qudt:SystemOfQuantityKinds-hasBaseQuantityKind,
        qudt:SystemOfQuantityKinds-hasQuantityKind,
        qudt:SystemOfQuantityKinds-hasUnitSystem,
        qudt:SystemOfQuantityKinds-systemDerivedQuantityKind .
```

The empty list at `sh:property [ ],` seems to be the cause. Removing it allows for an error-free import. Is that something that can be fixed at Brick?

**Comment by gtfierro** [comment]
I can look into this next week; the `+imports` file is produced automatically so tracking down this serialization error might be an issue. You can always handle the imports yourself (they are packaged in `imports.zip` in the release)

**Comment by steveraysteveray** [comment]
Hi. I manage the QUDT ontology, and I don't see that empty list in our repository, although you are correct that it seems to be there in Version 2.1.37 that was imported into Brick, so this is on us (QUDT). I will create a PR with Version 2.1.42 of QUDT imported. I would have to dig deeper to figure out why that empty list somehow made it into 2.1.37...
