### ISSUE TITLE
Inference with measures for Classes.

### ISSUE THREAD

**Issue by jbkoh** [BrickSchema/Brick#74]
I just noticed that ``brick:measures`` can determine Classes alone. For example,
```turtle
brick:Building_Static_Pressure_Sensor a owl:Class ;
    rdfs:label "Building Static Pressure Sensor" ;
    rdfs:subClassOf brick:Static_Pressure_Sensor ;
    owl:equivalentClass [ owl:intersectionOf ( [ a owl:Restriction ;
                        owl:hasValue brick:Pressure ;
                        owl:onProperty brick:measures ] [ a owl:Restriction ;
                        owl:hasValue brick:Air ;
                        owl:onProperty brick:measures ] ) ],
        [ owl:intersectionOf ( [ a owl:Restriction ;
                        owl:hasValue tag:Building ;
                        owl:onProperty brick:hasTag ] [ a owl:Restriction ;
                        owl:hasValue tag:Static ;
                        owl:onProperty brick:hasTag ] [ a owl:Restriction ;
                        owl:hasValue tag:Pressure ;
                        owl:onProperty brick:hasTag ] [ a owl:Restriction ;
                        owl:hasValue tag:Sensor ;
                        owl:onProperty brick:hasTag ] ) ] .
```
Here, there are two rules: with ``measures`` and ``hasTag``. An inference engine could infer classes only with ``measures``. However, there are many sensors measuring Air and Pressure other than this.

There can be two solutions

1. Define what can be measured throughout the Sensor hierarchy. For example, ``Building_Air`` can be a class that ``Building_Static_Pressure_Sensor`` measures, and then something measuring ``Building_Air`` and ``Pressure`` will be unique. This involves more complete design of "Quantity" and "Substance".

2. A simpler solution that works with our current design would be using ``rdfs:subClassOf`` for ``measures`` Restrictions instead of ``owl:equivalentClass``.

**Comment by JoelBender** [comment]
`Static_Pressure` is an [observable property](https://www.w3.org/TR/vocab-ssn/#SOSAObservableProperty) of air, so a `Building_Static_Pressure_Sensor` is a [sensor](https://www.w3.org/TR/vocab-ssn/#SOSASensor) of `Static_Pressure` associated with a `Building`.  I don't see a `Building_Air` definition, but it would seem that it would be narrower concept of `Air` (purposefully avoiding the subclass/superclass concepts).

The "current" building static pressure is an [observation](https://www.w3.org/TR/vocab-ssn/#SOSAObservation) made by the sensor, and should probably have some units.  In the case of  `bacnet:AnalogInputObject`, the `bacnet:units` property would come along for the ride.

**Comment by jbkoh** [comment]
Yeah, measuring ``Building_Air`` and ``Static_Pressure`` should be the right solution, but in the current implementation most of the ``measures`` for ``Sensors`` are missing, so I was curious if we should implement everything before the release or associate the ``Restirctions`` with ``rdfs:subClassOf`` instead of ``owl:equivalentClassOf``. You opinion seems backing the idea to add comprehensive ``measures`` relationships. This should be one of the two major fixes we need before the release.

**Comment by gtfierro** [comment]
I'm working on improving the coverage of `measures` relationships in https://github.com/BrickSchema/Brick/pull/76 (most recent commits have this done for most of the Sensor hierarchy).

I like the idea of trying `rdfs:subClassOf` instead of `owl:equivalentClass`. It has the potential of simplifying the reasoning while preserving the semantics we require.

**Comment by gtfierro** [comment]
I've written a test case to make sure that use of the `brick:measures` relationship leads to the correct inference of classes in PR #76, which should resolve this issue when it is merged
