### ISSUE TITLE
Rollback removed classes without discussions

### ISSUE THREAD

**Issue by jbkoh** [BrickSchema/Brick#82]
I would like to get back all the removed classes removed without discussions. I believe the general governance of Brick would be that any change should based on discussions 1) to minimize version bumps and 2) for consensus-based changes.

For example
- Emergency_Power_Off_System (i.e. EPO)
- Electricity_Meter
- All the Alarms
- Gas_Usage_Sensor
- Louver
- Smoke related points
- Standby_CRAC

I cannot enumerate all of them here for now. Though we can still remove them based on discussions, I want to defer such discussions for the next versions.

**Comment by gtfierro** [comment]
All of these changes were made in a PR that was approved by all parties (we even had a phone call!). I think the best way to go forward would be for you to list all of the points you want added and we can have the discussion in the PR

**Comment by jbkoh** [comment]
The changes and discussions were all about the structure not specific about the classes. It is unfair to ask all the interest parties to look through two different schemata line by line. The changes have become obvious after the diff tool. Any changes need reasoning about them while there is no reasoning for most of the changes in terms of classes. The default policy should be to inherit the previous version.

**Comment by gtfierro** [comment]
I agree that the policy should be to inherit the previous version. I attempted to only remove classes that were ambiguous, ill-defined or redundant, and it is definitely possible that I missed some.

@shreyasnagare in the process of handling #57 , can you make a note of classes in 1.0.3 that have no 1.1.0 equivalent? We can incorporate those into a future PR

**Comment by gtfierro** [comment]
@jbkoh can we close this?

**Comment by jbkoh** [comment]
A couple of classes above are still not defined. I will add them once we finalize the other parts of the code, and then close this one.

**Comment by gtfierro** [comment]
Does #108 fix the outstanding classes for this issue?

**Comment by jbkoh** [comment]
@gtfierro These seem still missing.
- Louver
- Standby_CRAC

**Comment by gtfierro** [comment]
This would have been great to know for #108 :)

Can you verify that https://github.com/BrickSchema/Brick/pull/111 closes this issue?

**Comment by jbkoh** [comment]
Done
