### ISSUE TITLE
Incorrect hierarchy in status subclasses

### ISSUE THREAD

**Issue by shreyasnagare** [BrickSchema/Brick#86]
The On/Off Status hierarchy looks incorrect. 

![Status Classes' Hierarchy](https://user-images.githubusercontent.com/12209457/67585095-eb47b180-f71c-11e9-964e-fa296f961d30.png)

## Problems:
- This forms the following two cycles:
  - `brick:On_Status` --rdfs:subClassOf --> brick:On_Off_Status --rdfs:subClassOf --> `brick:On_Status`
  - `brick:Off_Status` --rdfs:subClassOf --> brick:On_Off_Status --rdfs:subClassOf --> `brick:Off_Status`

- This makes these three classes (owl) equivalent to each other:
  - brick:On_Status
  - brick:Off_Status
  - brick:On_Off_Status

**Comment by gtfierro** [comment]
Good eye! This comes down to [status.py line 201](https://github.com/BrickSchema/Brick/blob/master/bricksrc/status.py#L201). I think it makes sense to adjust this so on_status and off_status are subclasses of on_off_status instead of the other way around. I'll submit a PR

**Comment by shreyasnagare** [comment]
> I think it makes sense to adjust this so on_status and off_status are subclasses of on_off_status instead of the other way around. I'll submit a PR.

I was thinking the other way around for two reasons (probably a very absurd way of thinking):
- I thought On_Status and Off_Status combine to form On_Off_Status. 
![Untitled Diagram (2)](https://user-images.githubusercontent.com/12209457/67599792-cb28ea00-f73e-11e9-8813-caab2ab32b52.png)

- I was expecting all the subclasses of `brick:On_Off_Status` to have the term `On_Off_Status` in it which `brick:On_Status` and `brick:Off_Status` don't. For instance:
    - brick:Cooling_On_Off_Status
    - brick:Humidification_On_Off_Status
    - brick:EconCycle_On_Off_Status
    - brick:Locally_On_Off_Status

**Comment by gtfierro** [comment]
You know, this isn't a bad design either! The trick is to choose the classes so that you're not accidentally inferring "across" elements of the hierarchy. I'm working on exploring both of these designs in a separate branch. My initial idea may not work as well, but I'll push one of them this afternoon so we can take a look at it. The design you just posted is essentially the original intended lattice; it may be best to just stick with that (but implement it properly, of course!)

**Comment by gtfierro** [comment]
@shreyasnagare let me know what you think of the fix!

**Comment by shreyasnagare** [comment]
@gtfierro That looks great!

**Comment by gtfierro** [comment]
Merged and fixed; thanks for your help :)
